# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: Y:/Documents/MesDocuments/Cours_nsave/Enseirb-E3_nsave/pr310/git/Xavier_commit/hls/main_module/solution1/impl/vhdl/top_level.xdc

# IP: ip/top_level_ap_dmul_4_max_dsp_64/top_level_ap_dmul_4_max_dsp_64.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_ap_dmul_4_max_dsp_64 || ORIG_REF_NAME==top_level_ap_dmul_4_max_dsp_64} -quiet] -quiet

# IP: ip/top_level_ap_dadddsub_4_full_dsp_64/top_level_ap_dadddsub_4_full_dsp_64.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_ap_dadddsub_4_full_dsp_64 || ORIG_REF_NAME==top_level_ap_dadddsub_4_full_dsp_64} -quiet] -quiet

# IP: ip/top_level_ap_fpext_0_no_dsp_32/top_level_ap_fpext_0_no_dsp_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_ap_fpext_0_no_dsp_32 || ORIG_REF_NAME==top_level_ap_fpext_0_no_dsp_32} -quiet] -quiet

# IP: ip/top_level_ap_fptrunc_0_no_dsp_64/top_level_ap_fptrunc_0_no_dsp_64.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_ap_fptrunc_0_no_dsp_64 || ORIG_REF_NAME==top_level_ap_fptrunc_0_no_dsp_64} -quiet] -quiet

# IP: ip/top_level_ap_fsqrt_10_no_dsp_32/top_level_ap_fsqrt_10_no_dsp_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_ap_fsqrt_10_no_dsp_32 || ORIG_REF_NAME==top_level_ap_fsqrt_10_no_dsp_32} -quiet] -quiet

# IP: ip/top_level_ap_sitofp_4_no_dsp_32/top_level_ap_sitofp_4_no_dsp_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_ap_sitofp_4_no_dsp_32 || ORIG_REF_NAME==top_level_ap_sitofp_4_no_dsp_32} -quiet] -quiet

# IP: ip/top_level_ap_fmul_2_max_dsp_32/top_level_ap_fmul_2_max_dsp_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_ap_fmul_2_max_dsp_32 || ORIG_REF_NAME==top_level_ap_fmul_2_max_dsp_32} -quiet] -quiet

# IP: ip/top_level_ap_dadd_4_full_dsp_64/top_level_ap_dadd_4_full_dsp_64.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_ap_dadd_4_full_dsp_64 || ORIG_REF_NAME==top_level_ap_dadd_4_full_dsp_64} -quiet] -quiet

# IP: ip/top_level_ap_fcmp_0_no_dsp_32/top_level_ap_fcmp_0_no_dsp_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_ap_fcmp_0_no_dsp_32 || ORIG_REF_NAME==top_level_ap_fcmp_0_no_dsp_32} -quiet] -quiet
