# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2017.3
# Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
# 
# ==============================================================

#
# Settings for Vivado implementation flow
#
set top_module top_level
set language vhdl
set family artix7
set device xc7a100t
set package csg324
set speed -1
set clock clk
set fsm_ext "off"

# For customizing the implementation flow
set add_io_buffers false ;# true|false
