// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.3
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="Conversion,hls_ip_2017_3,{HLS_INPUT_TYPE=sc,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100tcsg324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.816000,HLS_SYN_LAT=2,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=2,HLS_SYN_LUT=35}" *)

module Conversion (
        clk,
        reset,
        e_dout,
        e_empty_n,
        e_read,
        s_din,
        s_full_n,
        s_write
);


input   clk;
input   reset;
input  [7:0] e_dout;
input   e_empty_n;
output   e_read;
output  [7:0] s_din;
input   s_full_n;
output   s_write;

wire    grp_Conversion_do_conversion_fu_56_e_read;
wire   [7:0] grp_Conversion_do_conversion_fu_56_s_din;
wire    grp_Conversion_do_conversion_fu_56_s_write;

Conversion_do_conversion grp_Conversion_do_conversion_fu_56(
    .ap_clk(clk),
    .ap_rst(reset),
    .e_dout(e_dout),
    .e_empty_n(e_empty_n),
    .e_read(grp_Conversion_do_conversion_fu_56_e_read),
    .s_din(grp_Conversion_do_conversion_fu_56_s_din),
    .s_full_n(s_full_n),
    .s_write(grp_Conversion_do_conversion_fu_56_s_write)
);

assign e_read = grp_Conversion_do_conversion_fu_56_e_read;

assign s_din = grp_Conversion_do_conversion_fu_56_s_din;

assign s_write = grp_Conversion_do_conversion_fu_56_s_write;

endmodule //Conversion
