// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.3
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _comparateur_HH_
#define _comparateur_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "comparateur_do_comp.h"

namespace ap_rtl {

struct comparateur : public sc_module {
    // Port declarations 11
    sc_in_clk clk;
    sc_in< sc_logic > reset;
    sc_in< sc_lv<32> > e1_dout;
    sc_in< sc_logic > e1_empty_n;
    sc_out< sc_logic > e1_read;
    sc_in< sc_lv<32> > e2_dout;
    sc_in< sc_logic > e2_empty_n;
    sc_out< sc_logic > e2_read;
    sc_out< sc_lv<32> > s_din;
    sc_in< sc_logic > s_full_n;
    sc_out< sc_logic > s_write;


    // Module declarations
    comparateur(sc_module_name name);
    SC_HAS_PROCESS(comparateur);

    ~comparateur();

    sc_trace_file* mVcdFile;

    comparateur_do_comp* grp_comparateur_do_comp_fu_66;
    sc_signal< sc_lv<32> > grp_comparateur_do_comp_fu_66_comparateur_in1;
    sc_signal< sc_logic > grp_comparateur_do_comp_fu_66_comparateur_in1_ap_vld;
    sc_signal< sc_lv<32> > grp_comparateur_do_comp_fu_66_comparateur_seuil;
    sc_signal< sc_logic > grp_comparateur_do_comp_fu_66_comparateur_seuil_ap_vld;
    sc_signal< sc_lv<32> > grp_comparateur_do_comp_fu_66_comparateur_result;
    sc_signal< sc_logic > grp_comparateur_do_comp_fu_66_comparateur_result_ap_vld;
    sc_signal< sc_logic > grp_comparateur_do_comp_fu_66_e1_read;
    sc_signal< sc_logic > grp_comparateur_do_comp_fu_66_e2_read;
    sc_signal< sc_lv<32> > grp_comparateur_do_comp_fu_66_s_din;
    sc_signal< sc_logic > grp_comparateur_do_comp_fu_66_s_write;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_e1_read();
    void thread_e2_read();
    void thread_s_din();
    void thread_s_write();
};

}

using namespace ap_rtl;

#endif
