// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.3
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "filtre2.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic filtre2::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic filtre2::ap_const_logic_0 = sc_dt::Log_0;
const bool filtre2::ap_const_boolean_1 = true;

filtre2::filtre2(sc_module_name name) : sc_module(name), mVcdFile(0) {
    filtre2_mem_x_U = new filtre2_filtre2_mlbW("filtre2_mem_x_U");
    filtre2_mem_x_U->clk(ap_clk);
    filtre2_mem_x_U->reset(ap_rst);
    filtre2_mem_x_U->address0(grp_filtre2_do_filtre_fu_72_filtre2_mem_x_address0);
    filtre2_mem_x_U->ce0(grp_filtre2_do_filtre_fu_72_filtre2_mem_x_ce0);
    filtre2_mem_x_U->we0(grp_filtre2_do_filtre_fu_72_filtre2_mem_x_we0);
    filtre2_mem_x_U->d0(grp_filtre2_do_filtre_fu_72_filtre2_mem_x_d0);
    filtre2_mem_x_U->q0(filtre2_mem_x_q0);
    filtre2_mem_x_U->address1(grp_filtre2_do_filtre_fu_72_filtre2_mem_x_address1);
    filtre2_mem_x_U->ce1(grp_filtre2_do_filtre_fu_72_filtre2_mem_x_ce1);
    filtre2_mem_x_U->we1(grp_filtre2_do_filtre_fu_72_filtre2_mem_x_we1);
    filtre2_mem_x_U->d1(grp_filtre2_do_filtre_fu_72_filtre2_mem_x_d1);
    filtre2_mem_y_U = new filtre2_filtre2_mlbW("filtre2_mem_y_U");
    filtre2_mem_y_U->clk(ap_clk);
    filtre2_mem_y_U->reset(ap_rst);
    filtre2_mem_y_U->address0(grp_filtre2_do_filtre_fu_72_filtre2_mem_y_address0);
    filtre2_mem_y_U->ce0(grp_filtre2_do_filtre_fu_72_filtre2_mem_y_ce0);
    filtre2_mem_y_U->we0(grp_filtre2_do_filtre_fu_72_filtre2_mem_y_we0);
    filtre2_mem_y_U->d0(grp_filtre2_do_filtre_fu_72_filtre2_mem_y_d0);
    filtre2_mem_y_U->q0(filtre2_mem_y_q0);
    filtre2_mem_y_U->address1(grp_filtre2_do_filtre_fu_72_filtre2_mem_y_address1);
    filtre2_mem_y_U->ce1(grp_filtre2_do_filtre_fu_72_filtre2_mem_y_ce1);
    filtre2_mem_y_U->we1(grp_filtre2_do_filtre_fu_72_filtre2_mem_y_we1);
    filtre2_mem_y_U->d1(grp_filtre2_do_filtre_fu_72_filtre2_mem_y_d1);
    grp_filtre2_do_filtre_fu_72 = new filtre2_do_filtre("grp_filtre2_do_filtre_fu_72");
    grp_filtre2_do_filtre_fu_72->ap_clk(clk);
    grp_filtre2_do_filtre_fu_72->ap_rst(reset);
    grp_filtre2_do_filtre_fu_72->filtre2_y0(grp_filtre2_do_filtre_fu_72_filtre2_y0);
    grp_filtre2_do_filtre_fu_72->filtre2_y0_ap_vld(grp_filtre2_do_filtre_fu_72_filtre2_y0_ap_vld);
    grp_filtre2_do_filtre_fu_72->filtre2_x0(grp_filtre2_do_filtre_fu_72_filtre2_x0);
    grp_filtre2_do_filtre_fu_72->filtre2_x0_ap_vld(grp_filtre2_do_filtre_fu_72_filtre2_x0_ap_vld);
    grp_filtre2_do_filtre_fu_72->filtre2_mem_x_address0(grp_filtre2_do_filtre_fu_72_filtre2_mem_x_address0);
    grp_filtre2_do_filtre_fu_72->filtre2_mem_x_ce0(grp_filtre2_do_filtre_fu_72_filtre2_mem_x_ce0);
    grp_filtre2_do_filtre_fu_72->filtre2_mem_x_we0(grp_filtre2_do_filtre_fu_72_filtre2_mem_x_we0);
    grp_filtre2_do_filtre_fu_72->filtre2_mem_x_d0(grp_filtre2_do_filtre_fu_72_filtre2_mem_x_d0);
    grp_filtre2_do_filtre_fu_72->filtre2_mem_x_q0(filtre2_mem_x_q0);
    grp_filtre2_do_filtre_fu_72->filtre2_mem_x_address1(grp_filtre2_do_filtre_fu_72_filtre2_mem_x_address1);
    grp_filtre2_do_filtre_fu_72->filtre2_mem_x_ce1(grp_filtre2_do_filtre_fu_72_filtre2_mem_x_ce1);
    grp_filtre2_do_filtre_fu_72->filtre2_mem_x_we1(grp_filtre2_do_filtre_fu_72_filtre2_mem_x_we1);
    grp_filtre2_do_filtre_fu_72->filtre2_mem_x_d1(grp_filtre2_do_filtre_fu_72_filtre2_mem_x_d1);
    grp_filtre2_do_filtre_fu_72->filtre2_mem_y_address0(grp_filtre2_do_filtre_fu_72_filtre2_mem_y_address0);
    grp_filtre2_do_filtre_fu_72->filtre2_mem_y_ce0(grp_filtre2_do_filtre_fu_72_filtre2_mem_y_ce0);
    grp_filtre2_do_filtre_fu_72->filtre2_mem_y_we0(grp_filtre2_do_filtre_fu_72_filtre2_mem_y_we0);
    grp_filtre2_do_filtre_fu_72->filtre2_mem_y_d0(grp_filtre2_do_filtre_fu_72_filtre2_mem_y_d0);
    grp_filtre2_do_filtre_fu_72->filtre2_mem_y_q0(filtre2_mem_y_q0);
    grp_filtre2_do_filtre_fu_72->filtre2_mem_y_address1(grp_filtre2_do_filtre_fu_72_filtre2_mem_y_address1);
    grp_filtre2_do_filtre_fu_72->filtre2_mem_y_ce1(grp_filtre2_do_filtre_fu_72_filtre2_mem_y_ce1);
    grp_filtre2_do_filtre_fu_72->filtre2_mem_y_we1(grp_filtre2_do_filtre_fu_72_filtre2_mem_y_we1);
    grp_filtre2_do_filtre_fu_72->filtre2_mem_y_d1(grp_filtre2_do_filtre_fu_72_filtre2_mem_y_d1);
    grp_filtre2_do_filtre_fu_72->e_dout(e_dout);
    grp_filtre2_do_filtre_fu_72->e_empty_n(e_empty_n);
    grp_filtre2_do_filtre_fu_72->e_read(grp_filtre2_do_filtre_fu_72_e_read);
    grp_filtre2_do_filtre_fu_72->s_din(grp_filtre2_do_filtre_fu_72_s_din);
    grp_filtre2_do_filtre_fu_72->s_full_n(s_full_n);
    grp_filtre2_do_filtre_fu_72->s_write(grp_filtre2_do_filtre_fu_72_s_write);

    SC_METHOD(thread_e_read);
    sensitive << ( grp_filtre2_do_filtre_fu_72_e_read );

    SC_METHOD(thread_s_din);
    sensitive << ( grp_filtre2_do_filtre_fu_72_s_din );
    sensitive << ( grp_filtre2_do_filtre_fu_72_s_write );

    SC_METHOD(thread_s_write);
    sensitive << ( grp_filtre2_do_filtre_fu_72_s_write );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "filtre2_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, clk, "(port)clk");
    sc_trace(mVcdFile, reset, "(port)reset");
    sc_trace(mVcdFile, e_dout, "(port)e_dout");
    sc_trace(mVcdFile, e_empty_n, "(port)e_empty_n");
    sc_trace(mVcdFile, e_read, "(port)e_read");
    sc_trace(mVcdFile, s_din, "(port)s_din");
    sc_trace(mVcdFile, s_full_n, "(port)s_full_n");
    sc_trace(mVcdFile, s_write, "(port)s_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, filtre2_mem_x_q0, "filtre2_mem_x_q0");
    sc_trace(mVcdFile, filtre2_mem_y_q0, "filtre2_mem_y_q0");
    sc_trace(mVcdFile, grp_filtre2_do_filtre_fu_72_filtre2_y0, "grp_filtre2_do_filtre_fu_72_filtre2_y0");
    sc_trace(mVcdFile, grp_filtre2_do_filtre_fu_72_filtre2_y0_ap_vld, "grp_filtre2_do_filtre_fu_72_filtre2_y0_ap_vld");
    sc_trace(mVcdFile, grp_filtre2_do_filtre_fu_72_filtre2_x0, "grp_filtre2_do_filtre_fu_72_filtre2_x0");
    sc_trace(mVcdFile, grp_filtre2_do_filtre_fu_72_filtre2_x0_ap_vld, "grp_filtre2_do_filtre_fu_72_filtre2_x0_ap_vld");
    sc_trace(mVcdFile, grp_filtre2_do_filtre_fu_72_filtre2_mem_x_address0, "grp_filtre2_do_filtre_fu_72_filtre2_mem_x_address0");
    sc_trace(mVcdFile, grp_filtre2_do_filtre_fu_72_filtre2_mem_x_ce0, "grp_filtre2_do_filtre_fu_72_filtre2_mem_x_ce0");
    sc_trace(mVcdFile, grp_filtre2_do_filtre_fu_72_filtre2_mem_x_we0, "grp_filtre2_do_filtre_fu_72_filtre2_mem_x_we0");
    sc_trace(mVcdFile, grp_filtre2_do_filtre_fu_72_filtre2_mem_x_d0, "grp_filtre2_do_filtre_fu_72_filtre2_mem_x_d0");
    sc_trace(mVcdFile, grp_filtre2_do_filtre_fu_72_filtre2_mem_x_address1, "grp_filtre2_do_filtre_fu_72_filtre2_mem_x_address1");
    sc_trace(mVcdFile, grp_filtre2_do_filtre_fu_72_filtre2_mem_x_ce1, "grp_filtre2_do_filtre_fu_72_filtre2_mem_x_ce1");
    sc_trace(mVcdFile, grp_filtre2_do_filtre_fu_72_filtre2_mem_x_we1, "grp_filtre2_do_filtre_fu_72_filtre2_mem_x_we1");
    sc_trace(mVcdFile, grp_filtre2_do_filtre_fu_72_filtre2_mem_x_d1, "grp_filtre2_do_filtre_fu_72_filtre2_mem_x_d1");
    sc_trace(mVcdFile, grp_filtre2_do_filtre_fu_72_filtre2_mem_y_address0, "grp_filtre2_do_filtre_fu_72_filtre2_mem_y_address0");
    sc_trace(mVcdFile, grp_filtre2_do_filtre_fu_72_filtre2_mem_y_ce0, "grp_filtre2_do_filtre_fu_72_filtre2_mem_y_ce0");
    sc_trace(mVcdFile, grp_filtre2_do_filtre_fu_72_filtre2_mem_y_we0, "grp_filtre2_do_filtre_fu_72_filtre2_mem_y_we0");
    sc_trace(mVcdFile, grp_filtre2_do_filtre_fu_72_filtre2_mem_y_d0, "grp_filtre2_do_filtre_fu_72_filtre2_mem_y_d0");
    sc_trace(mVcdFile, grp_filtre2_do_filtre_fu_72_filtre2_mem_y_address1, "grp_filtre2_do_filtre_fu_72_filtre2_mem_y_address1");
    sc_trace(mVcdFile, grp_filtre2_do_filtre_fu_72_filtre2_mem_y_ce1, "grp_filtre2_do_filtre_fu_72_filtre2_mem_y_ce1");
    sc_trace(mVcdFile, grp_filtre2_do_filtre_fu_72_filtre2_mem_y_we1, "grp_filtre2_do_filtre_fu_72_filtre2_mem_y_we1");
    sc_trace(mVcdFile, grp_filtre2_do_filtre_fu_72_filtre2_mem_y_d1, "grp_filtre2_do_filtre_fu_72_filtre2_mem_y_d1");
    sc_trace(mVcdFile, grp_filtre2_do_filtre_fu_72_e_read, "grp_filtre2_do_filtre_fu_72_e_read");
    sc_trace(mVcdFile, grp_filtre2_do_filtre_fu_72_s_din, "grp_filtre2_do_filtre_fu_72_s_din");
    sc_trace(mVcdFile, grp_filtre2_do_filtre_fu_72_s_write, "grp_filtre2_do_filtre_fu_72_s_write");
#endif

    }
}

filtre2::~filtre2() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete filtre2_mem_x_U;
    delete filtre2_mem_y_U;
    delete grp_filtre2_do_filtre_fu_72;
}

void filtre2::thread_e_read() {
    e_read = grp_filtre2_do_filtre_fu_72_e_read.read();
}

void filtre2::thread_s_din() {
    s_din = grp_filtre2_do_filtre_fu_72_s_din.read();
}

void filtre2::thread_s_write() {
    s_write = grp_filtre2_do_filtre_fu_72_s_write.read();
}

}

