// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.3
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "filtre1_do_filtre.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic filtre1_do_filtre::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic filtre1_do_filtre::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<24> filtre1_do_filtre::ap_ST_fsm_state2 = "10";
const sc_lv<24> filtre1_do_filtre::ap_ST_fsm_state3 = "100";
const sc_lv<24> filtre1_do_filtre::ap_ST_fsm_state4 = "1000";
const sc_lv<24> filtre1_do_filtre::ap_ST_fsm_state5 = "10000";
const sc_lv<24> filtre1_do_filtre::ap_ST_fsm_state6 = "100000";
const sc_lv<24> filtre1_do_filtre::ap_ST_fsm_state7 = "1000000";
const sc_lv<24> filtre1_do_filtre::ap_ST_fsm_state8 = "10000000";
const sc_lv<24> filtre1_do_filtre::ap_ST_fsm_state9 = "100000000";
const sc_lv<24> filtre1_do_filtre::ap_ST_fsm_state10 = "1000000000";
const sc_lv<24> filtre1_do_filtre::ap_ST_fsm_state11 = "10000000000";
const sc_lv<24> filtre1_do_filtre::ap_ST_fsm_state12 = "100000000000";
const sc_lv<24> filtre1_do_filtre::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<24> filtre1_do_filtre::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<24> filtre1_do_filtre::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<24> filtre1_do_filtre::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<24> filtre1_do_filtre::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<24> filtre1_do_filtre::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<24> filtre1_do_filtre::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<24> filtre1_do_filtre::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<24> filtre1_do_filtre::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<24> filtre1_do_filtre::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<24> filtre1_do_filtre::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<24> filtre1_do_filtre::ap_ST_fsm_state24 = "100000000000000000000000";
const bool filtre1_do_filtre::ap_const_boolean_1 = true;
const sc_lv<32> filtre1_do_filtre::ap_const_lv32_2 = "10";
const sc_lv<1> filtre1_do_filtre::ap_const_lv1_0 = "0";
const sc_lv<32> filtre1_do_filtre::ap_const_lv32_17 = "10111";
const sc_lv<32> filtre1_do_filtre::ap_const_lv32_3 = "11";
const sc_lv<32> filtre1_do_filtre::ap_const_lv32_9 = "1001";
const sc_lv<32> filtre1_do_filtre::ap_const_lv32_F = "1111";
const sc_lv<32> filtre1_do_filtre::ap_const_lv32_15 = "10101";
const sc_lv<32> filtre1_do_filtre::ap_const_lv32_16 = "10110";
const sc_lv<2> filtre1_do_filtre::ap_const_lv2_0 = "00";
const sc_lv<32> filtre1_do_filtre::ap_const_lv32_1 = "1";
const sc_lv<64> filtre1_do_filtre::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<64> filtre1_do_filtre::ap_const_lv64_1 = "1";
const sc_lv<32> filtre1_do_filtre::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> filtre1_do_filtre::ap_const_lv32_8 = "1000";
const sc_lv<32> filtre1_do_filtre::ap_const_lv32_A = "1010";
const sc_lv<32> filtre1_do_filtre::ap_const_lv32_10 = "10000";
const sc_lv<64> filtre1_do_filtre::ap_const_lv64_3FEF800000000000 = "11111111101111100000000000000000000000000000000000000000000000";
const sc_lv<64> filtre1_do_filtre::ap_const_lv64_3FEF000000000000 = "11111111101111000000000000000000000000000000000000000000000000";
const sc_lv<32> filtre1_do_filtre::ap_const_lv32_4 = "100";
const sc_lv<2> filtre1_do_filtre::ap_const_lv2_2 = "10";
const sc_lv<2> filtre1_do_filtre::ap_const_lv2_1 = "1";
const sc_lv<1> filtre1_do_filtre::ap_const_lv1_1 = "1";

filtre1_do_filtre::filtre1_do_filtre(sc_module_name name) : sc_module(name), mVcdFile(0) {
    filtre1_fptrunc_6eOg_U36 = new filtre1_fptrunc_6eOg<1,1,64,32>("filtre1_fptrunc_6eOg_U36");
    filtre1_fptrunc_6eOg_U36->din0(reg_229);
    filtre1_fptrunc_6eOg_U36->dout(y_fu_191_p1);
    filtre1_fpext_32nfYi_U37 = new filtre1_fpext_32nfYi<1,1,32,64>("filtre1_fpext_32nfYi_U37");
    filtre1_fpext_32nfYi_U37->din0(grp_fu_195_p0);
    filtre1_fpext_32nfYi_U37->dout(grp_fu_195_p1);
    filtre1_fpext_32nfYi_U38 = new filtre1_fpext_32nfYi<1,1,32,64>("filtre1_fpext_32nfYi_U38");
    filtre1_fpext_32nfYi_U38->din0(filtre1_mem_x_q0);
    filtre1_fpext_32nfYi_U38->dout(tmp_4_fu_198_p1);
    filtre1_dadddsub_g8j_U39 = new filtre1_dadddsub_g8j<1,6,64,64,64>("filtre1_dadddsub_g8j_U39");
    filtre1_dadddsub_g8j_U39->clk(ap_clk);
    filtre1_dadddsub_g8j_U39->reset(ap_rst);
    filtre1_dadddsub_g8j_U39->din0(grp_fu_203_p0);
    filtre1_dadddsub_g8j_U39->din1(grp_fu_203_p1);
    filtre1_dadddsub_g8j_U39->opcode(grp_fu_203_opcode);
    filtre1_dadddsub_g8j_U39->ce(ap_var_for_const0);
    filtre1_dadddsub_g8j_U39->dout(grp_fu_203_p2);
    filtre1_dmul_64nshbi_U40 = new filtre1_dmul_64nshbi<1,6,64,64,64>("filtre1_dmul_64nshbi_U40");
    filtre1_dmul_64nshbi_U40->clk(ap_clk);
    filtre1_dmul_64nshbi_U40->reset(ap_rst);
    filtre1_dmul_64nshbi_U40->din0(reg_218);
    filtre1_dmul_64nshbi_U40->din1(grp_fu_207_p1);
    filtre1_dmul_64nshbi_U40->ce(ap_var_for_const0);
    filtre1_dmul_64nshbi_U40->dout(grp_fu_207_p2);
    filtre1_dmul_64nshbi_U41 = new filtre1_dmul_64nshbi<1,6,64,64,64>("filtre1_dmul_64nshbi_U41");
    filtre1_dmul_64nshbi_U41->clk(ap_clk);
    filtre1_dmul_64nshbi_U41->reset(ap_rst);
    filtre1_dmul_64nshbi_U41->din0(tmp_4_reg_280);
    filtre1_dmul_64nshbi_U41->din1(ap_var_for_const1);
    filtre1_dmul_64nshbi_U41->ce(ap_var_for_const0);
    filtre1_dmul_64nshbi_U41->dout(grp_fu_212_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state22);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state23);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state24);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state3);
    sensitive << ( e_empty_n );
    sensitive << ( exitcond_fu_235_p2 );

    SC_METHOD(thread_e_blk_n);
    sensitive << ( e_empty_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond_fu_235_p2 );

    SC_METHOD(thread_e_read);
    sensitive << ( e_empty_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond_fu_235_p2 );

    SC_METHOD(thread_exitcond_fu_235_p2);
    sensitive << ( e_empty_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond_fu_235_p2 );
    sensitive << ( i1_reg_180 );

    SC_METHOD(thread_filtre1_mem_x_addr_2_gep_fu_139_p3);
    sensitive << ( ap_rst );

    SC_METHOD(thread_filtre1_mem_x_addr_gep_fu_111_p3);
    sensitive << ( ap_rst );

    SC_METHOD(thread_filtre1_mem_x_address0);
    sensitive << ( ap_rst );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( filtre1_mem_x_addr_gep_fu_111_p3 );
    sensitive << ( tmp_s_fu_247_p1 );

    SC_METHOD(thread_filtre1_mem_x_address1);
    sensitive << ( ap_rst );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( filtre1_mem_x_addr_1_reg_274 );
    sensitive << ( filtre1_mem_x_addr_2_gep_fu_139_p3 );

    SC_METHOD(thread_filtre1_mem_x_ce0);
    sensitive << ( ap_rst );
    sensitive << ( e_empty_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond_fu_235_p2 );

    SC_METHOD(thread_filtre1_mem_x_ce1);
    sensitive << ( ap_rst );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_filtre1_mem_x_d0);
    sensitive << ( ap_rst );

    SC_METHOD(thread_filtre1_mem_x_d1);
    sensitive << ( ap_rst );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( val_reg_261 );

    SC_METHOD(thread_filtre1_mem_x_we0);
    sensitive << ( ap_rst );

    SC_METHOD(thread_filtre1_mem_x_we1);
    sensitive << ( ap_rst );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_filtre1_mem_y_addr_2_gep_fu_152_p3);
    sensitive << ( ap_rst );

    SC_METHOD(thread_filtre1_mem_y_addr_gep_fu_125_p3);
    sensitive << ( ap_rst );

    SC_METHOD(thread_filtre1_mem_y_address0);
    sensitive << ( ap_rst );
    sensitive << ( filtre1_mem_y_addr_1_reg_268 );
    sensitive << ( filtre1_mem_y_addr_gep_fu_125_p3 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_filtre1_mem_y_address1);
    sensitive << ( ap_rst );
    sensitive << ( filtre1_mem_y_addr_1_reg_268 );
    sensitive << ( ap_CS_fsm_state23 );
    sensitive << ( filtre1_mem_y_addr_2_gep_fu_152_p3 );

    SC_METHOD(thread_filtre1_mem_y_ce0);
    sensitive << ( ap_rst );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_filtre1_mem_y_ce1);
    sensitive << ( ap_rst );
    sensitive << ( ap_CS_fsm_state23 );

    SC_METHOD(thread_filtre1_mem_y_d0);
    sensitive << ( ap_rst );

    SC_METHOD(thread_filtre1_mem_y_d1);
    sensitive << ( ap_rst );
    sensitive << ( y_fu_191_p1 );
    sensitive << ( ap_CS_fsm_state23 );

    SC_METHOD(thread_filtre1_mem_y_we0);
    sensitive << ( ap_rst );

    SC_METHOD(thread_filtre1_mem_y_we1);
    sensitive << ( ap_rst );
    sensitive << ( ap_CS_fsm_state23 );

    SC_METHOD(thread_filtre1_x0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( val_reg_261 );

    SC_METHOD(thread_filtre1_x0_ap_vld);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_filtre1_y0);
    sensitive << ( s_full_n );
    sensitive << ( ap_CS_fsm_state24 );
    sensitive << ( y_reg_290 );

    SC_METHOD(thread_filtre1_y0_ap_vld);
    sensitive << ( s_full_n );
    sensitive << ( ap_CS_fsm_state24 );

    SC_METHOD(thread_grp_fu_195_p0);
    sensitive << ( filtre1_mem_y_q0 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( val_reg_261 );

    SC_METHOD(thread_grp_fu_203_opcode);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_grp_fu_203_p0);
    sensitive << ( reg_223 );
    sensitive << ( reg_229 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_grp_fu_203_p1);
    sensitive << ( reg_223 );
    sensitive << ( tmp_5_reg_285 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_grp_fu_207_p1);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_i_fu_241_p2);
    sensitive << ( i1_reg_180 );

    SC_METHOD(thread_s_blk_n);
    sensitive << ( s_full_n );
    sensitive << ( ap_CS_fsm_state24 );

    SC_METHOD(thread_s_din);
    sensitive << ( s_full_n );
    sensitive << ( ap_CS_fsm_state24 );
    sensitive << ( y_reg_290 );

    SC_METHOD(thread_s_write);
    sensitive << ( s_full_n );
    sensitive << ( ap_CS_fsm_state24 );

    SC_METHOD(thread_tmp_s_fu_247_p1);
    sensitive << ( i1_reg_180 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( e_empty_n );
    sensitive << ( s_full_n );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond_fu_235_p2 );
    sensitive << ( ap_CS_fsm_state24 );

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const1);

    ap_CS_fsm = "000000000000000000000010";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "filtre1_do_filtre_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, filtre1_y0, "(port)filtre1_y0");
    sc_trace(mVcdFile, filtre1_y0_ap_vld, "(port)filtre1_y0_ap_vld");
    sc_trace(mVcdFile, filtre1_x0, "(port)filtre1_x0");
    sc_trace(mVcdFile, filtre1_x0_ap_vld, "(port)filtre1_x0_ap_vld");
    sc_trace(mVcdFile, filtre1_mem_x_address0, "(port)filtre1_mem_x_address0");
    sc_trace(mVcdFile, filtre1_mem_x_ce0, "(port)filtre1_mem_x_ce0");
    sc_trace(mVcdFile, filtre1_mem_x_we0, "(port)filtre1_mem_x_we0");
    sc_trace(mVcdFile, filtre1_mem_x_d0, "(port)filtre1_mem_x_d0");
    sc_trace(mVcdFile, filtre1_mem_x_q0, "(port)filtre1_mem_x_q0");
    sc_trace(mVcdFile, filtre1_mem_x_address1, "(port)filtre1_mem_x_address1");
    sc_trace(mVcdFile, filtre1_mem_x_ce1, "(port)filtre1_mem_x_ce1");
    sc_trace(mVcdFile, filtre1_mem_x_we1, "(port)filtre1_mem_x_we1");
    sc_trace(mVcdFile, filtre1_mem_x_d1, "(port)filtre1_mem_x_d1");
    sc_trace(mVcdFile, filtre1_mem_y_address0, "(port)filtre1_mem_y_address0");
    sc_trace(mVcdFile, filtre1_mem_y_ce0, "(port)filtre1_mem_y_ce0");
    sc_trace(mVcdFile, filtre1_mem_y_we0, "(port)filtre1_mem_y_we0");
    sc_trace(mVcdFile, filtre1_mem_y_d0, "(port)filtre1_mem_y_d0");
    sc_trace(mVcdFile, filtre1_mem_y_q0, "(port)filtre1_mem_y_q0");
    sc_trace(mVcdFile, filtre1_mem_y_address1, "(port)filtre1_mem_y_address1");
    sc_trace(mVcdFile, filtre1_mem_y_ce1, "(port)filtre1_mem_y_ce1");
    sc_trace(mVcdFile, filtre1_mem_y_we1, "(port)filtre1_mem_y_we1");
    sc_trace(mVcdFile, filtre1_mem_y_d1, "(port)filtre1_mem_y_d1");
    sc_trace(mVcdFile, e_dout, "(port)e_dout");
    sc_trace(mVcdFile, e_empty_n, "(port)e_empty_n");
    sc_trace(mVcdFile, e_read, "(port)e_read");
    sc_trace(mVcdFile, s_din, "(port)s_din");
    sc_trace(mVcdFile, s_full_n, "(port)s_full_n");
    sc_trace(mVcdFile, s_write, "(port)s_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, e_blk_n, "e_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, exitcond_fu_235_p2, "exitcond_fu_235_p2");
    sc_trace(mVcdFile, s_blk_n, "s_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state24, "ap_CS_fsm_state24");
    sc_trace(mVcdFile, grp_fu_195_p1, "grp_fu_195_p1");
    sc_trace(mVcdFile, reg_218, "reg_218");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, grp_fu_207_p2, "grp_fu_207_p2");
    sc_trace(mVcdFile, reg_223, "reg_223");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, grp_fu_203_p2, "grp_fu_203_p2");
    sc_trace(mVcdFile, reg_229, "reg_229");
    sc_trace(mVcdFile, ap_CS_fsm_state22, "ap_CS_fsm_state22");
    sc_trace(mVcdFile, i_fu_241_p2, "i_fu_241_p2");
    sc_trace(mVcdFile, i_reg_256, "i_reg_256");
    sc_trace(mVcdFile, ap_block_state3, "ap_block_state3");
    sc_trace(mVcdFile, val_reg_261, "val_reg_261");
    sc_trace(mVcdFile, filtre1_mem_y_addr_1_reg_268, "filtre1_mem_y_addr_1_reg_268");
    sc_trace(mVcdFile, filtre1_mem_x_addr_1_reg_274, "filtre1_mem_x_addr_1_reg_274");
    sc_trace(mVcdFile, tmp_4_fu_198_p1, "tmp_4_fu_198_p1");
    sc_trace(mVcdFile, tmp_4_reg_280, "tmp_4_reg_280");
    sc_trace(mVcdFile, grp_fu_212_p2, "grp_fu_212_p2");
    sc_trace(mVcdFile, tmp_5_reg_285, "tmp_5_reg_285");
    sc_trace(mVcdFile, y_fu_191_p1, "y_fu_191_p1");
    sc_trace(mVcdFile, y_reg_290, "y_reg_290");
    sc_trace(mVcdFile, ap_CS_fsm_state23, "ap_CS_fsm_state23");
    sc_trace(mVcdFile, i1_reg_180, "i1_reg_180");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, filtre1_mem_x_addr_gep_fu_111_p3, "filtre1_mem_x_addr_gep_fu_111_p3");
    sc_trace(mVcdFile, filtre1_mem_y_addr_gep_fu_125_p3, "filtre1_mem_y_addr_gep_fu_125_p3");
    sc_trace(mVcdFile, filtre1_mem_x_addr_2_gep_fu_139_p3, "filtre1_mem_x_addr_2_gep_fu_139_p3");
    sc_trace(mVcdFile, filtre1_mem_y_addr_2_gep_fu_152_p3, "filtre1_mem_y_addr_2_gep_fu_152_p3");
    sc_trace(mVcdFile, tmp_s_fu_247_p1, "tmp_s_fu_247_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, grp_fu_195_p0, "grp_fu_195_p0");
    sc_trace(mVcdFile, grp_fu_203_p0, "grp_fu_203_p0");
    sc_trace(mVcdFile, grp_fu_203_p1, "grp_fu_203_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, grp_fu_207_p1, "grp_fu_207_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, grp_fu_203_opcode, "grp_fu_203_opcode");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

filtre1_do_filtre::~filtre1_do_filtre() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete filtre1_fptrunc_6eOg_U36;
    delete filtre1_fpext_32nfYi_U37;
    delete filtre1_fpext_32nfYi_U38;
    delete filtre1_dadddsub_g8j_U39;
    delete filtre1_dmul_64nshbi_U40;
    delete filtre1_dmul_64nshbi_U41;
}

void filtre1_do_filtre::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void filtre1_do_filtre::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv64_3FEF800000000000;
}

void filtre1_do_filtre::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state2;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read()) && 
         esl_seteq<1,1,1>(s_full_n.read(), ap_const_logic_1))) {
        i1_reg_180 = i_reg_256.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i1_reg_180 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(exitcond_fu_235_p2.read(), ap_const_lv1_0) && !(esl_seteq<1,1,1>(exitcond_fu_235_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read())))) {
        filtre1_mem_x_addr_1_reg_274 =  (sc_lv<1>) (tmp_s_fu_247_p1.read());
        filtre1_mem_y_addr_1_reg_268 =  (sc_lv<1>) (tmp_s_fu_247_p1.read());
        val_reg_261 = e_dout.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && !(esl_seteq<1,1,1>(exitcond_fu_235_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read())))) {
        i_reg_256 = i_fu_241_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        reg_218 = grp_fu_195_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()))) {
        reg_223 = grp_fu_207_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read()))) {
        reg_229 = grp_fu_203_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        tmp_4_reg_280 = tmp_4_fu_198_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        tmp_5_reg_285 = grp_fu_212_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read())) {
        y_reg_290 = y_fu_191_p1.read();
    }
}

void filtre1_do_filtre::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void filtre1_do_filtre::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void filtre1_do_filtre::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read()[15];
}

void filtre1_do_filtre::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read()[16];
}

void filtre1_do_filtre::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void filtre1_do_filtre::thread_ap_CS_fsm_state22() {
    ap_CS_fsm_state22 = ap_CS_fsm.read()[21];
}

void filtre1_do_filtre::thread_ap_CS_fsm_state23() {
    ap_CS_fsm_state23 = ap_CS_fsm.read()[22];
}

void filtre1_do_filtre::thread_ap_CS_fsm_state24() {
    ap_CS_fsm_state24 = ap_CS_fsm.read()[23];
}

void filtre1_do_filtre::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void filtre1_do_filtre::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void filtre1_do_filtre::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void filtre1_do_filtre::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void filtre1_do_filtre::thread_ap_block_state3() {
    ap_block_state3 = (esl_seteq<1,1,1>(exitcond_fu_235_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()));
}

void filtre1_do_filtre::thread_e_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(exitcond_fu_235_p2.read(), ap_const_lv1_0))) {
        e_blk_n = e_empty_n.read();
    } else {
        e_blk_n = ap_const_logic_1;
    }
}

void filtre1_do_filtre::thread_e_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(exitcond_fu_235_p2.read(), ap_const_lv1_0) && 
         !(esl_seteq<1,1,1>(exitcond_fu_235_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read())))) {
        e_read = ap_const_logic_1;
    } else {
        e_read = ap_const_logic_0;
    }
}

void filtre1_do_filtre::thread_exitcond_fu_235_p2() {
    exitcond_fu_235_p2 = (!i1_reg_180.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(i1_reg_180.read() == ap_const_lv2_2);
}

void filtre1_do_filtre::thread_filtre1_mem_x_addr_2_gep_fu_139_p3() {
    if ( ap_rst.read() == ap_const_logic_1) {
        filtre1_mem_x_addr_2_gep_fu_139_p3 =  (sc_lv<1>) (ap_const_lv64_1);
    } else {
        filtre1_mem_x_addr_2_gep_fu_139_p3 =  (sc_lv<1>) (ap_const_lv64_1);
    }
}

void filtre1_do_filtre::thread_filtre1_mem_x_addr_gep_fu_111_p3() {
    if ( ap_rst.read() == ap_const_logic_1) {
        filtre1_mem_x_addr_gep_fu_111_p3 =  (sc_lv<1>) (ap_const_lv64_0);
    } else {
        filtre1_mem_x_addr_gep_fu_111_p3 =  (sc_lv<1>) (ap_const_lv64_0);
    }
}

void filtre1_do_filtre::thread_filtre1_mem_x_address0() {
    if ( ap_rst.read() == ap_const_logic_1) {
        filtre1_mem_x_address0 = filtre1_mem_x_addr_gep_fu_111_p3.read();
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
            filtre1_mem_x_address0 =  (sc_lv<1>) (tmp_s_fu_247_p1.read());
        } else if (!esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
            filtre1_mem_x_address0 =  (sc_lv<1>) (ap_const_lv64_0);
        } else {
            filtre1_mem_x_address0 = "X";
        }
    }
}

void filtre1_do_filtre::thread_filtre1_mem_x_address1() {
    if ( ap_rst.read() == ap_const_logic_1) {
        filtre1_mem_x_address1 = filtre1_mem_x_addr_2_gep_fu_139_p3.read();
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
            filtre1_mem_x_address1 = filtre1_mem_x_addr_1_reg_274.read();
        } else if (!esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
            filtre1_mem_x_address1 =  (sc_lv<1>) (ap_const_lv64_1);
        } else {
            filtre1_mem_x_address1 = "X";
        }
    }
}

void filtre1_do_filtre::thread_filtre1_mem_x_ce0() {
    if ( ap_rst.read() == ap_const_logic_1) {
        filtre1_mem_x_ce0 = ap_const_logic_1;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
             !(esl_seteq<1,1,1>(exitcond_fu_235_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read())))) {
            filtre1_mem_x_ce0 = ap_const_logic_1;
        } else {
            filtre1_mem_x_ce0 = ap_const_logic_0;
        }
    }
}

void filtre1_do_filtre::thread_filtre1_mem_x_ce1() {
    if ( ap_rst.read() == ap_const_logic_1) {
        filtre1_mem_x_ce1 = ap_const_logic_1;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
            filtre1_mem_x_ce1 = ap_const_logic_1;
        } else {
            filtre1_mem_x_ce1 = ap_const_logic_0;
        }
    }
}

void filtre1_do_filtre::thread_filtre1_mem_x_d0() {
    if ( ap_rst.read() == ap_const_logic_1) {
        filtre1_mem_x_d0 = ap_const_lv32_0;
    } else {
        filtre1_mem_x_d0 = ap_const_lv32_0;
    }
}

void filtre1_do_filtre::thread_filtre1_mem_x_d1() {
    if ( ap_rst.read() == ap_const_logic_1) {
        filtre1_mem_x_d1 = ap_const_lv32_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
            filtre1_mem_x_d1 = val_reg_261.read();
        } else if (!esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
            filtre1_mem_x_d1 = ap_const_lv32_0;
        } else {
            filtre1_mem_x_d1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
        }
    }
}

void filtre1_do_filtre::thread_filtre1_mem_x_we0() {
    if ( ap_rst.read() == ap_const_logic_1) {
        filtre1_mem_x_we0 = ap_const_logic_1;
    } else {
        if (!esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
            filtre1_mem_x_we0 = ap_const_logic_1;
        } else {
            filtre1_mem_x_we0 = ap_const_logic_0;
        }
    }
}

void filtre1_do_filtre::thread_filtre1_mem_x_we1() {
    if ( ap_rst.read() == ap_const_logic_1) {
        filtre1_mem_x_we1 = ap_const_logic_1;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
            filtre1_mem_x_we1 = ap_const_logic_1;
        } else {
            filtre1_mem_x_we1 = ap_const_logic_0;
        }
    }
}

void filtre1_do_filtre::thread_filtre1_mem_y_addr_2_gep_fu_152_p3() {
    if ( ap_rst.read() == ap_const_logic_1) {
        filtre1_mem_y_addr_2_gep_fu_152_p3 =  (sc_lv<1>) (ap_const_lv64_1);
    } else {
        filtre1_mem_y_addr_2_gep_fu_152_p3 =  (sc_lv<1>) (ap_const_lv64_1);
    }
}

void filtre1_do_filtre::thread_filtre1_mem_y_addr_gep_fu_125_p3() {
    if ( ap_rst.read() == ap_const_logic_1) {
        filtre1_mem_y_addr_gep_fu_125_p3 =  (sc_lv<1>) (ap_const_lv64_0);
    } else {
        filtre1_mem_y_addr_gep_fu_125_p3 =  (sc_lv<1>) (ap_const_lv64_0);
    }
}

void filtre1_do_filtre::thread_filtre1_mem_y_address0() {
    if ( ap_rst.read() == ap_const_logic_1) {
        filtre1_mem_y_address0 = filtre1_mem_y_addr_gep_fu_125_p3.read();
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
            filtre1_mem_y_address0 = filtre1_mem_y_addr_1_reg_268.read();
        } else if (!esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
            filtre1_mem_y_address0 =  (sc_lv<1>) (ap_const_lv64_0);
        } else {
            filtre1_mem_y_address0 = "X";
        }
    }
}

void filtre1_do_filtre::thread_filtre1_mem_y_address1() {
    if ( ap_rst.read() == ap_const_logic_1) {
        filtre1_mem_y_address1 = filtre1_mem_y_addr_2_gep_fu_152_p3.read();
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read())) {
            filtre1_mem_y_address1 = filtre1_mem_y_addr_1_reg_268.read();
        } else if (!esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
            filtre1_mem_y_address1 =  (sc_lv<1>) (ap_const_lv64_1);
        } else {
            filtre1_mem_y_address1 = "X";
        }
    }
}

void filtre1_do_filtre::thread_filtre1_mem_y_ce0() {
    if ( ap_rst.read() == ap_const_logic_1) {
        filtre1_mem_y_ce0 = ap_const_logic_1;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
            filtre1_mem_y_ce0 = ap_const_logic_1;
        } else {
            filtre1_mem_y_ce0 = ap_const_logic_0;
        }
    }
}

void filtre1_do_filtre::thread_filtre1_mem_y_ce1() {
    if ( ap_rst.read() == ap_const_logic_1) {
        filtre1_mem_y_ce1 = ap_const_logic_1;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read())) {
            filtre1_mem_y_ce1 = ap_const_logic_1;
        } else {
            filtre1_mem_y_ce1 = ap_const_logic_0;
        }
    }
}

void filtre1_do_filtre::thread_filtre1_mem_y_d0() {
    if ( ap_rst.read() == ap_const_logic_1) {
        filtre1_mem_y_d0 = ap_const_lv32_0;
    } else {
        filtre1_mem_y_d0 = ap_const_lv32_0;
    }
}

void filtre1_do_filtre::thread_filtre1_mem_y_d1() {
    if ( ap_rst.read() == ap_const_logic_1) {
        filtre1_mem_y_d1 = ap_const_lv32_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read())) {
            filtre1_mem_y_d1 = y_fu_191_p1.read();
        } else if (!esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
            filtre1_mem_y_d1 = ap_const_lv32_0;
        } else {
            filtre1_mem_y_d1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
        }
    }
}

void filtre1_do_filtre::thread_filtre1_mem_y_we0() {
    if ( ap_rst.read() == ap_const_logic_1) {
        filtre1_mem_y_we0 = ap_const_logic_1;
    } else {
        if (!esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
            filtre1_mem_y_we0 = ap_const_logic_1;
        } else {
            filtre1_mem_y_we0 = ap_const_logic_0;
        }
    }
}

void filtre1_do_filtre::thread_filtre1_mem_y_we1() {
    if ( ap_rst.read() == ap_const_logic_1) {
        filtre1_mem_y_we1 = ap_const_logic_1;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read())) {
            filtre1_mem_y_we1 = ap_const_logic_1;
        } else {
            filtre1_mem_y_we1 = ap_const_logic_0;
        }
    }
}

void filtre1_do_filtre::thread_filtre1_x0() {
    filtre1_x0 = val_reg_261.read();
}

void filtre1_do_filtre::thread_filtre1_x0_ap_vld() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        filtre1_x0_ap_vld = ap_const_logic_1;
    } else {
        filtre1_x0_ap_vld = ap_const_logic_0;
    }
}

void filtre1_do_filtre::thread_filtre1_y0() {
    filtre1_y0 = y_reg_290.read();
}

void filtre1_do_filtre::thread_filtre1_y0_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read()) && 
         esl_seteq<1,1,1>(s_full_n.read(), ap_const_logic_1))) {
        filtre1_y0_ap_vld = ap_const_logic_1;
    } else {
        filtre1_y0_ap_vld = ap_const_logic_0;
    }
}

void filtre1_do_filtre::thread_grp_fu_195_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        grp_fu_195_p0 = filtre1_mem_y_q0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        grp_fu_195_p0 = val_reg_261.read();
    } else {
        grp_fu_195_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void filtre1_do_filtre::thread_grp_fu_203_opcode() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        grp_fu_203_opcode = ap_const_lv2_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        grp_fu_203_opcode = ap_const_lv2_0;
    } else {
        grp_fu_203_opcode =  (sc_lv<2>) ("XX");
    }
}

void filtre1_do_filtre::thread_grp_fu_203_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        grp_fu_203_p0 = reg_229.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        grp_fu_203_p0 = reg_223.read();
    } else {
        grp_fu_203_p0 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void filtre1_do_filtre::thread_grp_fu_203_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        grp_fu_203_p1 = reg_223.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        grp_fu_203_p1 = tmp_5_reg_285.read();
    } else {
        grp_fu_203_p1 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void filtre1_do_filtre::thread_grp_fu_207_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        grp_fu_207_p1 = ap_const_lv64_3FEF000000000000;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        grp_fu_207_p1 = ap_const_lv64_3FEF800000000000;
    } else {
        grp_fu_207_p1 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void filtre1_do_filtre::thread_i_fu_241_p2() {
    i_fu_241_p2 = (!i1_reg_180.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(i1_reg_180.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void filtre1_do_filtre::thread_s_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read())) {
        s_blk_n = s_full_n.read();
    } else {
        s_blk_n = ap_const_logic_1;
    }
}

void filtre1_do_filtre::thread_s_din() {
    s_din = y_reg_290.read();
}

void filtre1_do_filtre::thread_s_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read()) && 
         esl_seteq<1,1,1>(s_full_n.read(), ap_const_logic_1))) {
        s_write = ap_const_logic_1;
    } else {
        s_write = ap_const_logic_0;
    }
}

void filtre1_do_filtre::thread_tmp_s_fu_247_p1() {
    tmp_s_fu_247_p1 = esl_zext<64,2>(i1_reg_180.read());
}

void filtre1_do_filtre::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && !(esl_seteq<1,1,1>(exitcond_fu_235_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read())) && esl_seteq<1,1,1>(exitcond_fu_235_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(exitcond_fu_235_p2.read(), ap_const_lv1_0) && !(esl_seteq<1,1,1>(exitcond_fu_235_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read())))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state20;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_fsm_state21;
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_fsm_state22;
            break;
        case 2097152 : 
            ap_NS_fsm = ap_ST_fsm_state23;
            break;
        case 4194304 : 
            ap_NS_fsm = ap_ST_fsm_state24;
            break;
        case 8388608 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read()) && esl_seteq<1,1,1>(s_full_n.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state24;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<24>) ("XXXXXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

}

