// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.3
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _racine_HH_
#define _racine_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "racine_do_racine.h"

namespace ap_rtl {

struct racine : public sc_module {
    // Port declarations 8
    sc_in_clk clk;
    sc_in< sc_logic > reset;
    sc_in< sc_lv<32> > e_dout;
    sc_in< sc_logic > e_empty_n;
    sc_out< sc_logic > e_read;
    sc_out< sc_lv<32> > s_din;
    sc_in< sc_logic > s_full_n;
    sc_out< sc_logic > s_write;


    // Module declarations
    racine(sc_module_name name);
    SC_HAS_PROCESS(racine);

    ~racine();

    sc_trace_file* mVcdFile;

    racine_do_racine* grp_racine_do_racine_fu_58;
    sc_signal< sc_lv<32> > grp_racine_do_racine_fu_58_racine_x;
    sc_signal< sc_logic > grp_racine_do_racine_fu_58_racine_x_ap_vld;
    sc_signal< sc_logic > grp_racine_do_racine_fu_58_e_read;
    sc_signal< sc_lv<32> > grp_racine_do_racine_fu_58_s_din;
    sc_signal< sc_logic > grp_racine_do_racine_fu_58_s_write;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_e_read();
    void thread_s_din();
    void thread_s_write();
};

}

using namespace ap_rtl;

#endif
