// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.3
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "UartModOut_do_send.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic UartModOut_do_send::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic UartModOut_do_send::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<5> UartModOut_do_send::ap_ST_fsm_state2 = "10";
const sc_lv<5> UartModOut_do_send::ap_ST_fsm_state3 = "100";
const sc_lv<5> UartModOut_do_send::ap_ST_fsm_state4 = "1000";
const sc_lv<5> UartModOut_do_send::ap_ST_fsm_state5 = "10000";
const sc_lv<32> UartModOut_do_send::ap_const_lv32_1 = "1";
const sc_lv<32> UartModOut_do_send::ap_const_lv32_2 = "10";
const sc_lv<32> UartModOut_do_send::ap_const_lv32_3 = "11";
const sc_lv<32> UartModOut_do_send::ap_const_lv32_4 = "100";
const sc_lv<32> UartModOut_do_send::ap_const_lv32_8 = "1000";
const sc_lv<32> UartModOut_do_send::ap_const_lv32_F = "1111";
const sc_lv<32> UartModOut_do_send::ap_const_lv32_10 = "10000";
const sc_lv<32> UartModOut_do_send::ap_const_lv32_17 = "10111";
const sc_lv<32> UartModOut_do_send::ap_const_lv32_18 = "11000";
const sc_lv<32> UartModOut_do_send::ap_const_lv32_1F = "11111";
const bool UartModOut_do_send::ap_const_boolean_1 = true;

UartModOut_do_send::UartModOut_do_send(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state2);
    sensitive << ( e_empty_n );
    sensitive << ( s_full_n );

    SC_METHOD(thread_e_blk_n);
    sensitive << ( e_empty_n );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_e_read);
    sensitive << ( e_empty_n );
    sensitive << ( s_full_n );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_s_blk_n);
    sensitive << ( s_full_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_s_din);
    sensitive << ( e_empty_n );
    sensitive << ( s_full_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_9_reg_118 );
    sensitive << ( tmp_11_reg_123 );
    sensitive << ( tmp_13_reg_128 );
    sensitive << ( tmp_29_fu_83_p1 );

    SC_METHOD(thread_s_write);
    sensitive << ( e_empty_n );
    sensitive << ( s_full_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_tmp28_fu_79_p1);
    sensitive << ( e_dout );

    SC_METHOD(thread_tmp_29_fu_83_p1);
    sensitive << ( tmp28_fu_79_p1 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( e_empty_n );
    sensitive << ( s_full_n );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );

    ap_CS_fsm = "00010";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "UartModOut_do_send_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, e_dout, "(port)e_dout");
    sc_trace(mVcdFile, e_empty_n, "(port)e_empty_n");
    sc_trace(mVcdFile, e_read, "(port)e_read");
    sc_trace(mVcdFile, s_din, "(port)s_din");
    sc_trace(mVcdFile, s_full_n, "(port)s_full_n");
    sc_trace(mVcdFile, s_write, "(port)s_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, e_blk_n, "e_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, s_blk_n, "s_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, tmp_9_reg_118, "tmp_9_reg_118");
    sc_trace(mVcdFile, ap_block_state2, "ap_block_state2");
    sc_trace(mVcdFile, tmp_11_reg_123, "tmp_11_reg_123");
    sc_trace(mVcdFile, tmp_13_reg_128, "tmp_13_reg_128");
    sc_trace(mVcdFile, tmp_29_fu_83_p1, "tmp_29_fu_83_p1");
    sc_trace(mVcdFile, tmp28_fu_79_p1, "tmp28_fu_79_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

UartModOut_do_send::~UartModOut_do_send() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void UartModOut_do_send::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state2;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, s_full_n.read())))) {
        tmp_11_reg_123 = tmp28_fu_79_p1.read().range(23, 16);
        tmp_13_reg_128 = tmp28_fu_79_p1.read().range(31, 24);
        tmp_9_reg_118 = tmp28_fu_79_p1.read().range(15, 8);
    }
}

void UartModOut_do_send::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void UartModOut_do_send::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void UartModOut_do_send::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void UartModOut_do_send::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void UartModOut_do_send::thread_ap_block_state2() {
    ap_block_state2 = (esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, s_full_n.read()));
}

void UartModOut_do_send::thread_e_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        e_blk_n = e_empty_n.read();
    } else {
        e_blk_n = ap_const_logic_1;
    }
}

void UartModOut_do_send::thread_e_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, s_full_n.read())))) {
        e_read = ap_const_logic_1;
    } else {
        e_read = ap_const_logic_0;
    }
}

void UartModOut_do_send::thread_s_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        s_blk_n = s_full_n.read();
    } else {
        s_blk_n = ap_const_logic_1;
    }
}

void UartModOut_do_send::thread_s_din() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(s_full_n.read(), ap_const_logic_1))) {
        s_din = tmp_13_reg_128.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(s_full_n.read(), ap_const_logic_1))) {
        s_din = tmp_11_reg_123.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(s_full_n.read(), ap_const_logic_1))) {
        s_din = tmp_9_reg_118.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, s_full_n.read())))) {
        s_din = tmp_29_fu_83_p1.read();
    } else {
        s_din = "XXXXXXXX";
    }
}

void UartModOut_do_send::thread_s_write() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          !(esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, s_full_n.read()))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          esl_seteq<1,1,1>(s_full_n.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
          esl_seteq<1,1,1>(s_full_n.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          esl_seteq<1,1,1>(s_full_n.read(), ap_const_logic_1)))) {
        s_write = ap_const_logic_1;
    } else {
        s_write = ap_const_logic_0;
    }
}

void UartModOut_do_send::thread_tmp28_fu_79_p1() {
    tmp28_fu_79_p1 = e_dout.read();
}

void UartModOut_do_send::thread_tmp_29_fu_83_p1() {
    tmp_29_fu_83_p1 = tmp28_fu_79_p1.read().range(8-1, 0);
}

void UartModOut_do_send::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, s_full_n.read())))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(s_full_n.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(s_full_n.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(s_full_n.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<5>) ("XXXXX");
            break;
    }
}

}

