// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.3
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "uart_wrapper.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic uart_wrapper::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic uart_wrapper::ap_const_logic_0 = sc_dt::Log_0;
const bool uart_wrapper::ap_const_boolean_1 = true;

uart_wrapper::uart_wrapper(sc_module_name name) : sc_module(name), mVcdFile(0) {
    grp_top_level_fu_190 = new top_level("grp_top_level_fu_190");
    grp_top_level_fu_190->e_dout(FIFO_I_1_dout);
    grp_top_level_fu_190->e_empty_n(FIFO_I_1_empty_n);
    grp_top_level_fu_190->e_read(grp_top_level_fu_190_e_read);
    grp_top_level_fu_190->s_din(grp_top_level_fu_190_s_din);
    grp_top_level_fu_190->s_full_n(FIFO_O_1_full_n);
    grp_top_level_fu_190->s_write(grp_top_level_fu_190_s_write);
    grp_top_level_fu_190->clk(clk);
    grp_top_level_fu_190->reset(reset);
    grp_uart_wrapper_do_action2_fu_306 = new uart_wrapper_do_action2("grp_uart_wrapper_do_action2_fu_306");
    grp_uart_wrapper_do_action2_fu_306->ap_clk(clk);
    grp_uart_wrapper_do_action2_fu_306->ap_rst(reset);
    grp_uart_wrapper_do_action2_fu_306->s_din(grp_uart_wrapper_do_action2_fu_306_s_din);
    grp_uart_wrapper_do_action2_fu_306->s_full_n(s_full_n);
    grp_uart_wrapper_do_action2_fu_306->s_write(grp_uart_wrapper_do_action2_fu_306_s_write);
    grp_uart_wrapper_do_action2_fu_306->FIFO_O_1_dout(FIFO_O_1_dout);
    grp_uart_wrapper_do_action2_fu_306->FIFO_O_1_empty_n(FIFO_O_1_empty_n);
    grp_uart_wrapper_do_action2_fu_306->FIFO_O_1_read(grp_uart_wrapper_do_action2_fu_306_FIFO_O_1_read);
    grp_uart_wrapper_do_action1_fu_422 = new uart_wrapper_do_action1("grp_uart_wrapper_do_action1_fu_422");
    grp_uart_wrapper_do_action1_fu_422->ap_clk(clk);
    grp_uart_wrapper_do_action1_fu_422->ap_rst(reset);
    grp_uart_wrapper_do_action1_fu_422->e_dout(e_dout);
    grp_uart_wrapper_do_action1_fu_422->e_empty_n(e_empty_n);
    grp_uart_wrapper_do_action1_fu_422->e_read(grp_uart_wrapper_do_action1_fu_422_e_read);
    grp_uart_wrapper_do_action1_fu_422->FIFO_I_1_din(grp_uart_wrapper_do_action1_fu_422_FIFO_I_1_din);
    grp_uart_wrapper_do_action1_fu_422->FIFO_I_1_full_n(FIFO_I_1_full_n);
    grp_uart_wrapper_do_action1_fu_422->FIFO_I_1_write(grp_uart_wrapper_do_action1_fu_422_FIFO_I_1_write);
    FIFO_I_1_fifo_U = new fifo_w32_d192_A("FIFO_I_1_fifo_U");
    FIFO_I_1_fifo_U->clk(clk);
    FIFO_I_1_fifo_U->reset(reset);
    FIFO_I_1_fifo_U->if_read_ce(ap_var_for_const0);
    FIFO_I_1_fifo_U->if_write_ce(ap_var_for_const0);
    FIFO_I_1_fifo_U->if_din(grp_uart_wrapper_do_action1_fu_422_FIFO_I_1_din);
    FIFO_I_1_fifo_U->if_full_n(FIFO_I_1_full_n);
    FIFO_I_1_fifo_U->if_write(grp_uart_wrapper_do_action1_fu_422_FIFO_I_1_write);
    FIFO_I_1_fifo_U->if_dout(FIFO_I_1_dout);
    FIFO_I_1_fifo_U->if_empty_n(FIFO_I_1_empty_n);
    FIFO_I_1_fifo_U->if_read(grp_top_level_fu_190_e_read);
    FIFO_O_1_fifo_U = new fifo_w32_d192_A("FIFO_O_1_fifo_U");
    FIFO_O_1_fifo_U->clk(clk);
    FIFO_O_1_fifo_U->reset(reset);
    FIFO_O_1_fifo_U->if_read_ce(ap_var_for_const0);
    FIFO_O_1_fifo_U->if_write_ce(ap_var_for_const0);
    FIFO_O_1_fifo_U->if_din(grp_top_level_fu_190_s_din);
    FIFO_O_1_fifo_U->if_full_n(FIFO_O_1_full_n);
    FIFO_O_1_fifo_U->if_write(grp_top_level_fu_190_s_write);
    FIFO_O_1_fifo_U->if_dout(FIFO_O_1_dout);
    FIFO_O_1_fifo_U->if_empty_n(FIFO_O_1_empty_n);
    FIFO_O_1_fifo_U->if_read(grp_uart_wrapper_do_action2_fu_306_FIFO_O_1_read);

    SC_METHOD(thread_e_read);
    sensitive << ( grp_uart_wrapper_do_action1_fu_422_e_read );

    SC_METHOD(thread_s_din);
    sensitive << ( grp_uart_wrapper_do_action2_fu_306_s_din );
    sensitive << ( grp_uart_wrapper_do_action2_fu_306_s_write );

    SC_METHOD(thread_s_write);
    sensitive << ( grp_uart_wrapper_do_action2_fu_306_s_write );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "uart_wrapper_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, clk, "(port)clk");
    sc_trace(mVcdFile, reset, "(port)reset");
    sc_trace(mVcdFile, e_dout, "(port)e_dout");
    sc_trace(mVcdFile, e_empty_n, "(port)e_empty_n");
    sc_trace(mVcdFile, e_read, "(port)e_read");
    sc_trace(mVcdFile, s_din, "(port)s_din");
    sc_trace(mVcdFile, s_full_n, "(port)s_full_n");
    sc_trace(mVcdFile, s_write, "(port)s_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, grp_top_level_fu_190_e_read, "grp_top_level_fu_190_e_read");
    sc_trace(mVcdFile, grp_top_level_fu_190_s_din, "grp_top_level_fu_190_s_din");
    sc_trace(mVcdFile, grp_top_level_fu_190_s_write, "grp_top_level_fu_190_s_write");
    sc_trace(mVcdFile, grp_uart_wrapper_do_action2_fu_306_s_din, "grp_uart_wrapper_do_action2_fu_306_s_din");
    sc_trace(mVcdFile, grp_uart_wrapper_do_action2_fu_306_s_write, "grp_uart_wrapper_do_action2_fu_306_s_write");
    sc_trace(mVcdFile, grp_uart_wrapper_do_action2_fu_306_FIFO_O_1_read, "grp_uart_wrapper_do_action2_fu_306_FIFO_O_1_read");
    sc_trace(mVcdFile, grp_uart_wrapper_do_action1_fu_422_e_read, "grp_uart_wrapper_do_action1_fu_422_e_read");
    sc_trace(mVcdFile, grp_uart_wrapper_do_action1_fu_422_FIFO_I_1_din, "grp_uart_wrapper_do_action1_fu_422_FIFO_I_1_din");
    sc_trace(mVcdFile, grp_uart_wrapper_do_action1_fu_422_FIFO_I_1_write, "grp_uart_wrapper_do_action1_fu_422_FIFO_I_1_write");
    sc_trace(mVcdFile, FIFO_O_1_dout, "FIFO_O_1_dout");
    sc_trace(mVcdFile, FIFO_O_1_empty_n, "FIFO_O_1_empty_n");
    sc_trace(mVcdFile, FIFO_I_1_full_n, "FIFO_I_1_full_n");
    sc_trace(mVcdFile, FIFO_I_1_dout, "FIFO_I_1_dout");
    sc_trace(mVcdFile, FIFO_I_1_empty_n, "FIFO_I_1_empty_n");
    sc_trace(mVcdFile, FIFO_O_1_full_n, "FIFO_O_1_full_n");
#endif

    }
    mHdltvinHandle.open("uart_wrapper.hdltvin.dat");
    mHdltvoutHandle.open("uart_wrapper.hdltvout.dat");
}

uart_wrapper::~uart_wrapper() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete grp_top_level_fu_190;
    delete grp_uart_wrapper_do_action2_fu_306;
    delete grp_uart_wrapper_do_action1_fu_422;
    delete FIFO_I_1_fifo_U;
    delete FIFO_O_1_fifo_U;
}

void uart_wrapper::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void uart_wrapper::thread_e_read() {
    e_read = grp_uart_wrapper_do_action1_fu_422_e_read.read();
}

void uart_wrapper::thread_s_din() {
    s_din = grp_uart_wrapper_do_action2_fu_306_s_din.read();
}

void uart_wrapper::thread_s_write() {
    s_write = grp_uart_wrapper_do_action2_fu_306_s_write.read();
}

void uart_wrapper::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"reset\" :  \"" << reset.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"e_dout\" :  \"" << e_dout.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"e_empty_n\" :  \"" << e_empty_n.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"e_read\" :  \"" << e_read.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_din\" :  \"" << s_din.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_full_n\" :  \"" << s_full_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_write\" :  \"" << s_write.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

