// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.3
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _UartModIn_HH_
#define _UartModIn_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "UartModIn_do_recv.h"

namespace ap_rtl {

struct UartModIn : public sc_module {
    // Port declarations 8
    sc_in< sc_lv<8> > e_dout;
    sc_in< sc_logic > e_empty_n;
    sc_out< sc_logic > e_read;
    sc_out< sc_lv<32> > s_din;
    sc_in< sc_logic > s_full_n;
    sc_out< sc_logic > s_write;
    sc_in_clk clk;
    sc_in< sc_logic > rst;


    // Module declarations
    UartModIn(sc_module_name name);
    SC_HAS_PROCESS(UartModIn);

    ~UartModIn();

    sc_trace_file* mVcdFile;

    UartModIn_do_recv* grp_UartModIn_do_recv_fu_58;
    sc_signal< sc_logic > grp_UartModIn_do_recv_fu_58_e_read;
    sc_signal< sc_lv<32> > grp_UartModIn_do_recv_fu_58_s_din;
    sc_signal< sc_logic > grp_UartModIn_do_recv_fu_58_s_write;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_e_read();
    void thread_s_din();
    void thread_s_write();
};

}

using namespace ap_rtl;

#endif
