<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE boost_serialization>
<boost_serialization signature="serialization::archive" version="15">
  <syndb class_id="0" tracking_level="0" version="0">
    <userIPLatency>-1</userIPLatency>
    <userIPName/>
    <cdfg class_id="1" tracking_level="1" version="0" object_id="_0">
      <name>uart_wrapper_oled</name>
      <ret_bitwidth>0</ret_bitwidth>
      <ports class_id="2" tracking_level="0" version="0">
        <count>6</count>
        <item_version>0</item_version>
        <item class_id="3" tracking_level="1" version="0" object_id="_1">
          <Value class_id="4" tracking_level="0" version="0">
            <Obj class_id="5" tracking_level="0" version="0">
              <type>1</type>
              <id>1</id>
              <name>clk</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo class_id="6" tracking_level="0" version="0">
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName>uart_wrapper_oled.clk.m_if.Val</originalName>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>1</bitwidth>
          </Value>
          <direction>0</direction>
          <if_type>0</if_type>
          <array_size>0</array_size>
          <bit_vecs class_id="7" tracking_level="0" version="0">
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
        <item class_id_reference="3" object_id="_2">
          <Value>
            <Obj>
              <type>1</type>
              <id>2</id>
              <name>reset</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName>uart_wrapper_oled.reset.m_if.Val</originalName>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>1</bitwidth>
          </Value>
          <direction>0</direction>
          <if_type>0</if_type>
          <array_size>0</array_size>
          <bit_vecs>
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
        <item class_id_reference="3" object_id="_3">
          <Value>
            <Obj>
              <type>1</type>
              <id>3</id>
              <name>e</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName>uart_wrapper_oled.e.m_if.Val</originalName>
              <rtlName/>
              <coreName>FIFO_SRL</coreName>
            </Obj>
            <bitwidth>8</bitwidth>
          </Value>
          <direction>0</direction>
          <if_type>3</if_type>
          <array_size>0</array_size>
          <bit_vecs>
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
        <item class_id_reference="3" object_id="_4">
          <Value>
            <Obj>
              <type>1</type>
              <id>4</id>
              <name>s</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName>uart_wrapper_oled.s.m_if.Val</originalName>
              <rtlName/>
              <coreName>FIFO_SRL</coreName>
            </Obj>
            <bitwidth>8</bitwidth>
          </Value>
          <direction>1</direction>
          <if_type>3</if_type>
          <array_size>0</array_size>
          <bit_vecs>
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
        <item class_id_reference="3" object_id="_5">
          <Value>
            <Obj>
              <type>1</type>
              <id>5</id>
              <name>en</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName>uart_wrapper_oled.en.m_if.Val</originalName>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>1</bitwidth>
          </Value>
          <direction>1</direction>
          <if_type>0</if_type>
          <array_size>0</array_size>
          <bit_vecs>
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
        <item class_id_reference="3" object_id="_6">
          <Value>
            <Obj>
              <type>1</type>
              <id>6</id>
              <name>s_i</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName>uart_wrapper_oled.s_i.m_if.Val.V</originalName>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>6</bitwidth>
          </Value>
          <direction>1</direction>
          <if_type>0</if_type>
          <array_size>0</array_size>
          <bit_vecs>
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
      </ports>
      <nodes class_id="8" tracking_level="0" version="0">
        <count>11</count>
        <item_version>0</item_version>
        <item class_id="9" tracking_level="1" version="0" object_id="_7">
          <Value>
            <Obj>
              <type>0</type>
              <id>42</id>
              <name/>
              <fileName>src/modules/oled_process.h</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>22</lineNumber>
              <contextFuncName>oled_process</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item class_id="10" tracking_level="0" version="0">
                  <first>Y:\Documents\MesDocuments\Cours_nsave\Enseirb-E3_nsave\pr310\git\Xavier_commit\hls</first>
                  <second class_id="11" tracking_level="0" version="0">
                    <count>2</count>
                    <item_version>0</item_version>
                    <item class_id="12" tracking_level="0" version="0">
                      <first class_id="13" tracking_level="0" version="0">
                        <first>src/modules/oled_process.h</first>
                        <second>oled_process</second>
                      </first>
                      <second>22</second>
                    </item>
                    <item>
                      <first>
                        <first>src/modules/uart_wrapper_oled.h</first>
                        <second>uart_wrapper_oled</second>
                      </first>
                      <second>33</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName>grp_oled_process_fu_106</rtlName>
              <coreName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>10</count>
            <item_version>0</item_version>
            <item>85</item>
            <item>86</item>
            <item>87</item>
            <item>88</item>
            <item>89</item>
            <item>90</item>
            <item>91</item>
            <item>92</item>
            <item>93</item>
            <item>140</item>
          </oprand_edges>
          <opcode>call</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_8">
          <Value>
            <Obj>
              <type>0</type>
              <id>48</id>
              <name>uart_wrapper_oled_s</name>
              <fileName>src/modules/uart_wrapper_oled.h</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>35</lineNumber>
              <contextFuncName>uart_wrapper_oled</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>Y:\Documents\MesDocuments\Cours_nsave\Enseirb-E3_nsave\pr310\git\Xavier_commit\hls</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>src/modules/uart_wrapper_oled.h</first>
                        <second>uart_wrapper_oled</second>
                      </first>
                      <second>35</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>1</bitwidth>
          </Value>
          <oprand_edges>
            <count>1</count>
            <item_version>0</item_version>
            <item>94</item>
          </oprand_edges>
          <opcode>load</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_9">
          <Value>
            <Obj>
              <type>0</type>
              <id>49</id>
              <name/>
              <fileName>src/modules/uart_wrapper_oled.h</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>35</lineNumber>
              <contextFuncName>uart_wrapper_oled</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>Y:\Documents\MesDocuments\Cours_nsave\Enseirb-E3_nsave\pr310\git\Xavier_commit\hls</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>src/modules/uart_wrapper_oled.h</first>
                        <second>uart_wrapper_oled</second>
                      </first>
                      <second>35</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>3</count>
            <item_version>0</item_version>
            <item>95</item>
            <item>96</item>
            <item>97</item>
          </oprand_edges>
          <opcode>br</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_10">
          <Value>
            <Obj>
              <type>0</type>
              <id>54</id>
              <name>uart_wrapper_oled_1</name>
              <fileName>src/modules/uart_wrapper_oled.h</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>38</lineNumber>
              <contextFuncName>uart_wrapper_oled</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>Y:\Documents\MesDocuments\Cours_nsave\Enseirb-E3_nsave\pr310\git\Xavier_commit\hls</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>src/modules/uart_wrapper_oled.h</first>
                        <second>uart_wrapper_oled</second>
                      </first>
                      <second>38</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>1</bitwidth>
          </Value>
          <oprand_edges>
            <count>1</count>
            <item_version>0</item_version>
            <item>117</item>
          </oprand_edges>
          <opcode>load</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_11">
          <Value>
            <Obj>
              <type>0</type>
              <id>55</id>
              <name/>
              <fileName>src/modules/uart_wrapper_oled.h</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>38</lineNumber>
              <contextFuncName>uart_wrapper_oled</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>Y:\Documents\MesDocuments\Cours_nsave\Enseirb-E3_nsave\pr310\git\Xavier_commit\hls</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>src/modules/uart_wrapper_oled.h</first>
                        <second>uart_wrapper_oled</second>
                      </first>
                      <second>38</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>3</count>
            <item_version>0</item_version>
            <item>118</item>
            <item>119</item>
            <item>120</item>
          </oprand_edges>
          <opcode>br</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_12">
          <Value>
            <Obj>
              <type>0</type>
              <id>74</id>
              <name/>
              <fileName>src/modules/uart_wrapper_oled.h</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>46</lineNumber>
              <contextFuncName>uart_wrapper_oled</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>Y:\Documents\MesDocuments\Cours_nsave\Enseirb-E3_nsave\pr310\git\Xavier_commit\hls</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>src/modules/uart_wrapper_oled.h</first>
                        <second>uart_wrapper_oled</second>
                      </first>
                      <second>46</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>0</count>
            <item_version>0</item_version>
          </oprand_edges>
          <opcode>ret</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_13">
          <Value>
            <Obj>
              <type>0</type>
              <id>76</id>
              <name/>
              <fileName>src/modules/uart_wrapper_oled.h</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>38</lineNumber>
              <contextFuncName>uart_wrapper_oled</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>Y:\Documents\MesDocuments\Cours_nsave\Enseirb-E3_nsave\pr310\git\Xavier_commit\hls</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>src/modules/uart_wrapper_oled.h</first>
                        <second>uart_wrapper_oled</second>
                      </first>
                      <second>38</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName>grp_uart_wrapper_oled_do_action2_fu_128</rtlName>
              <coreName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>21</count>
            <item_version>0</item_version>
            <item>122</item>
            <item>123</item>
            <item>124</item>
            <item>125</item>
            <item>126</item>
            <item>127</item>
            <item>128</item>
            <item>129</item>
            <item>130</item>
            <item>131</item>
            <item>132</item>
            <item>133</item>
            <item>134</item>
            <item>135</item>
            <item>136</item>
            <item>137</item>
            <item>138</item>
            <item>478</item>
            <item>480</item>
            <item>482</item>
            <item>484</item>
          </oprand_edges>
          <opcode>call</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_14">
          <Value>
            <Obj>
              <type>0</type>
              <id>77</id>
              <name/>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>1</count>
            <item_version>0</item_version>
            <item>139</item>
          </oprand_edges>
          <opcode>br</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_15">
          <Value>
            <Obj>
              <type>0</type>
              <id>79</id>
              <name/>
              <fileName>src/modules/uart_wrapper_oled.h</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>35</lineNumber>
              <contextFuncName>uart_wrapper_oled</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>Y:\Documents\MesDocuments\Cours_nsave\Enseirb-E3_nsave\pr310\git\Xavier_commit\hls</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>src/modules/uart_wrapper_oled.h</first>
                        <second>uart_wrapper_oled</second>
                      </first>
                      <second>35</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName>grp_uart_wrapper_oled_do_action1_fu_164</rtlName>
              <coreName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>21</count>
            <item_version>0</item_version>
            <item>99</item>
            <item>100</item>
            <item>101</item>
            <item>102</item>
            <item>103</item>
            <item>104</item>
            <item>105</item>
            <item>106</item>
            <item>107</item>
            <item>108</item>
            <item>109</item>
            <item>110</item>
            <item>111</item>
            <item>112</item>
            <item>113</item>
            <item>114</item>
            <item>115</item>
            <item>477</item>
            <item>479</item>
            <item>481</item>
            <item>483</item>
          </oprand_edges>
          <opcode>call</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_16">
          <Value>
            <Obj>
              <type>0</type>
              <id>80</id>
              <name/>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>1</count>
            <item_version>0</item_version>
            <item>116</item>
          </oprand_edges>
          <opcode>br</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_17">
          <Value>
            <Obj>
              <type>0</type>
              <id>82</id>
              <name/>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>0</count>
            <item_version>0</item_version>
          </oprand_edges>
          <opcode>unreachable</opcode>
          <m_Display>0</m_Display>
        </item>
      </nodes>
      <consts class_id="15" tracking_level="0" version="0">
        <count>3</count>
        <item_version>0</item_version>
        <item class_id="16" tracking_level="1" version="0" object_id="_18">
          <Value>
            <Obj>
              <type>2</type>
              <id>84</id>
              <name>oled_process</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <const_type>6</const_type>
          <content>&lt;constant:oled_process::oled_process.1&gt;</content>
        </item>
        <item class_id_reference="16" object_id="_19">
          <Value>
            <Obj>
              <type>2</type>
              <id>98</id>
              <name>uart_wrapper_oled_do_action1</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <const_type>6</const_type>
          <content>&lt;constant:uart_wrapper_oled::do_action1&gt;</content>
        </item>
        <item class_id_reference="16" object_id="_20">
          <Value>
            <Obj>
              <type>2</type>
              <id>121</id>
              <name>uart_wrapper_oled_do_action2</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <const_type>6</const_type>
          <content>&lt;constant:uart_wrapper_oled::do_action2&gt;</content>
        </item>
      </consts>
      <blocks class_id="17" tracking_level="0" version="0">
        <count>6</count>
        <item_version>0</item_version>
        <item class_id="18" tracking_level="1" version="0" object_id="_21">
          <Obj>
            <type>3</type>
            <id>50</id>
            <name/>
            <fileName/>
            <fileDirectory/>
            <lineNumber>0</lineNumber>
            <contextFuncName/>
            <inlineStackInfo>
              <count>0</count>
              <item_version>0</item_version>
            </inlineStackInfo>
            <originalName/>
            <rtlName/>
            <coreName/>
          </Obj>
          <node_objs>
            <count>3</count>
            <item_version>0</item_version>
            <item>42</item>
            <item>48</item>
            <item>49</item>
          </node_objs>
        </item>
        <item class_id_reference="18" object_id="_22">
          <Obj>
            <type>3</type>
            <id>56</id>
            <name/>
            <fileName/>
            <fileDirectory/>
            <lineNumber>0</lineNumber>
            <contextFuncName/>
            <inlineStackInfo>
              <count>0</count>
              <item_version>0</item_version>
            </inlineStackInfo>
            <originalName/>
            <rtlName/>
            <coreName/>
          </Obj>
          <node_objs>
            <count>2</count>
            <item_version>0</item_version>
            <item>54</item>
            <item>55</item>
          </node_objs>
        </item>
        <item class_id_reference="18" object_id="_23">
          <Obj>
            <type>3</type>
            <id>75</id>
            <name/>
            <fileName/>
            <fileDirectory/>
            <lineNumber>0</lineNumber>
            <contextFuncName/>
            <inlineStackInfo>
              <count>0</count>
              <item_version>0</item_version>
            </inlineStackInfo>
            <originalName/>
            <rtlName/>
            <coreName/>
          </Obj>
          <node_objs>
            <count>1</count>
            <item_version>0</item_version>
            <item>74</item>
          </node_objs>
        </item>
        <item class_id_reference="18" object_id="_24">
          <Obj>
            <type>3</type>
            <id>78</id>
            <name/>
            <fileName/>
            <fileDirectory/>
            <lineNumber>0</lineNumber>
            <contextFuncName/>
            <inlineStackInfo>
              <count>0</count>
              <item_version>0</item_version>
            </inlineStackInfo>
            <originalName/>
            <rtlName/>
            <coreName/>
          </Obj>
          <node_objs>
            <count>2</count>
            <item_version>0</item_version>
            <item>76</item>
            <item>77</item>
          </node_objs>
        </item>
        <item class_id_reference="18" object_id="_25">
          <Obj>
            <type>3</type>
            <id>81</id>
            <name/>
            <fileName/>
            <fileDirectory/>
            <lineNumber>0</lineNumber>
            <contextFuncName/>
            <inlineStackInfo>
              <count>0</count>
              <item_version>0</item_version>
            </inlineStackInfo>
            <originalName/>
            <rtlName/>
            <coreName/>
          </Obj>
          <node_objs>
            <count>2</count>
            <item_version>0</item_version>
            <item>79</item>
            <item>80</item>
          </node_objs>
        </item>
        <item class_id_reference="18" object_id="_26">
          <Obj>
            <type>3</type>
            <id>83</id>
            <name>UnifiedUnreachableBlock</name>
            <fileName/>
            <fileDirectory/>
            <lineNumber>0</lineNumber>
            <contextFuncName/>
            <inlineStackInfo>
              <count>0</count>
              <item_version>0</item_version>
            </inlineStackInfo>
            <originalName/>
            <rtlName/>
            <coreName/>
          </Obj>
          <node_objs>
            <count>1</count>
            <item_version>0</item_version>
            <item>82</item>
          </node_objs>
        </item>
      </blocks>
      <edges class_id="19" tracking_level="0" version="0">
        <count>68</count>
        <item_version>0</item_version>
        <item class_id="20" tracking_level="1" version="0" object_id="_27">
          <id>85</id>
          <edge_type>1</edge_type>
          <source_obj>84</source_obj>
          <sink_obj>42</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_28">
          <id>86</id>
          <edge_type>1</edge_type>
          <source_obj>7</source_obj>
          <sink_obj>42</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_29">
          <id>87</id>
          <edge_type>1</edge_type>
          <source_obj>8</source_obj>
          <sink_obj>42</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_30">
          <id>88</id>
          <edge_type>1</edge_type>
          <source_obj>9</source_obj>
          <sink_obj>42</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_31">
          <id>89</id>
          <edge_type>1</edge_type>
          <source_obj>10</source_obj>
          <sink_obj>42</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_32">
          <id>90</id>
          <edge_type>1</edge_type>
          <source_obj>11</source_obj>
          <sink_obj>42</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_33">
          <id>91</id>
          <edge_type>1</edge_type>
          <source_obj>12</source_obj>
          <sink_obj>42</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_34">
          <id>92</id>
          <edge_type>1</edge_type>
          <source_obj>13</source_obj>
          <sink_obj>42</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_35">
          <id>93</id>
          <edge_type>1</edge_type>
          <source_obj>14</source_obj>
          <sink_obj>42</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_36">
          <id>94</id>
          <edge_type>1</edge_type>
          <source_obj>18</source_obj>
          <sink_obj>48</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_37">
          <id>95</id>
          <edge_type>1</edge_type>
          <source_obj>48</source_obj>
          <sink_obj>49</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_38">
          <id>96</id>
          <edge_type>2</edge_type>
          <source_obj>56</source_obj>
          <sink_obj>49</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_39">
          <id>97</id>
          <edge_type>2</edge_type>
          <source_obj>81</source_obj>
          <sink_obj>49</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_40">
          <id>99</id>
          <edge_type>1</edge_type>
          <source_obj>98</source_obj>
          <sink_obj>79</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_41">
          <id>100</id>
          <edge_type>1</edge_type>
          <source_obj>1</source_obj>
          <sink_obj>79</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_42">
          <id>101</id>
          <edge_type>1</edge_type>
          <source_obj>2</source_obj>
          <sink_obj>79</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_43">
          <id>102</id>
          <edge_type>1</edge_type>
          <source_obj>3</source_obj>
          <sink_obj>79</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_44">
          <id>103</id>
          <edge_type>1</edge_type>
          <source_obj>4</source_obj>
          <sink_obj>79</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_45">
          <id>104</id>
          <edge_type>1</edge_type>
          <source_obj>5</source_obj>
          <sink_obj>79</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_46">
          <id>105</id>
          <edge_type>1</edge_type>
          <source_obj>6</source_obj>
          <sink_obj>79</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_47">
          <id>106</id>
          <edge_type>1</edge_type>
          <source_obj>7</source_obj>
          <sink_obj>79</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_48">
          <id>107</id>
          <edge_type>1</edge_type>
          <source_obj>8</source_obj>
          <sink_obj>79</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_49">
          <id>108</id>
          <edge_type>1</edge_type>
          <source_obj>9</source_obj>
          <sink_obj>79</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_50">
          <id>109</id>
          <edge_type>1</edge_type>
          <source_obj>10</source_obj>
          <sink_obj>79</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_51">
          <id>110</id>
          <edge_type>1</edge_type>
          <source_obj>11</source_obj>
          <sink_obj>79</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_52">
          <id>111</id>
          <edge_type>1</edge_type>
          <source_obj>12</source_obj>
          <sink_obj>79</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_53">
          <id>112</id>
          <edge_type>1</edge_type>
          <source_obj>13</source_obj>
          <sink_obj>79</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_54">
          <id>113</id>
          <edge_type>1</edge_type>
          <source_obj>14</source_obj>
          <sink_obj>79</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_55">
          <id>114</id>
          <edge_type>1</edge_type>
          <source_obj>15</source_obj>
          <sink_obj>79</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_56">
          <id>115</id>
          <edge_type>1</edge_type>
          <source_obj>16</source_obj>
          <sink_obj>79</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_57">
          <id>116</id>
          <edge_type>2</edge_type>
          <source_obj>83</source_obj>
          <sink_obj>80</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_58">
          <id>117</id>
          <edge_type>1</edge_type>
          <source_obj>19</source_obj>
          <sink_obj>54</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_59">
          <id>118</id>
          <edge_type>1</edge_type>
          <source_obj>54</source_obj>
          <sink_obj>55</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_60">
          <id>119</id>
          <edge_type>2</edge_type>
          <source_obj>75</source_obj>
          <sink_obj>55</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_61">
          <id>120</id>
          <edge_type>2</edge_type>
          <source_obj>78</source_obj>
          <sink_obj>55</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_62">
          <id>122</id>
          <edge_type>1</edge_type>
          <source_obj>121</source_obj>
          <sink_obj>76</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_63">
          <id>123</id>
          <edge_type>1</edge_type>
          <source_obj>1</source_obj>
          <sink_obj>76</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_64">
          <id>124</id>
          <edge_type>1</edge_type>
          <source_obj>2</source_obj>
          <sink_obj>76</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_65">
          <id>125</id>
          <edge_type>1</edge_type>
          <source_obj>3</source_obj>
          <sink_obj>76</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_66">
          <id>126</id>
          <edge_type>1</edge_type>
          <source_obj>4</source_obj>
          <sink_obj>76</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_67">
          <id>127</id>
          <edge_type>1</edge_type>
          <source_obj>5</source_obj>
          <sink_obj>76</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_68">
          <id>128</id>
          <edge_type>1</edge_type>
          <source_obj>6</source_obj>
          <sink_obj>76</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_69">
          <id>129</id>
          <edge_type>1</edge_type>
          <source_obj>7</source_obj>
          <sink_obj>76</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_70">
          <id>130</id>
          <edge_type>1</edge_type>
          <source_obj>8</source_obj>
          <sink_obj>76</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_71">
          <id>131</id>
          <edge_type>1</edge_type>
          <source_obj>9</source_obj>
          <sink_obj>76</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_72">
          <id>132</id>
          <edge_type>1</edge_type>
          <source_obj>10</source_obj>
          <sink_obj>76</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_73">
          <id>133</id>
          <edge_type>1</edge_type>
          <source_obj>11</source_obj>
          <sink_obj>76</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_74">
          <id>134</id>
          <edge_type>1</edge_type>
          <source_obj>12</source_obj>
          <sink_obj>76</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_75">
          <id>135</id>
          <edge_type>1</edge_type>
          <source_obj>13</source_obj>
          <sink_obj>76</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_76">
          <id>136</id>
          <edge_type>1</edge_type>
          <source_obj>14</source_obj>
          <sink_obj>76</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_77">
          <id>137</id>
          <edge_type>1</edge_type>
          <source_obj>15</source_obj>
          <sink_obj>76</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_78">
          <id>138</id>
          <edge_type>1</edge_type>
          <source_obj>16</source_obj>
          <sink_obj>76</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_79">
          <id>139</id>
          <edge_type>2</edge_type>
          <source_obj>83</source_obj>
          <sink_obj>77</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_80">
          <id>140</id>
          <edge_type>1</edge_type>
          <source_obj>17</source_obj>
          <sink_obj>42</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_81">
          <id>471</id>
          <edge_type>2</edge_type>
          <source_obj>50</source_obj>
          <sink_obj>81</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_82">
          <id>472</id>
          <edge_type>2</edge_type>
          <source_obj>50</source_obj>
          <sink_obj>56</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_83">
          <id>473</id>
          <edge_type>2</edge_type>
          <source_obj>56</source_obj>
          <sink_obj>78</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_84">
          <id>474</id>
          <edge_type>2</edge_type>
          <source_obj>56</source_obj>
          <sink_obj>75</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_85">
          <id>475</id>
          <edge_type>2</edge_type>
          <source_obj>78</source_obj>
          <sink_obj>83</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_86">
          <id>476</id>
          <edge_type>2</edge_type>
          <source_obj>81</source_obj>
          <sink_obj>83</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_87">
          <id>477</id>
          <edge_type>4</edge_type>
          <source_obj>42</source_obj>
          <sink_obj>79</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_88">
          <id>478</id>
          <edge_type>4</edge_type>
          <source_obj>42</source_obj>
          <sink_obj>76</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_89">
          <id>479</id>
          <edge_type>4</edge_type>
          <source_obj>42</source_obj>
          <sink_obj>79</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_90">
          <id>480</id>
          <edge_type>4</edge_type>
          <source_obj>42</source_obj>
          <sink_obj>76</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_91">
          <id>481</id>
          <edge_type>4</edge_type>
          <source_obj>42</source_obj>
          <sink_obj>79</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_92">
          <id>482</id>
          <edge_type>4</edge_type>
          <source_obj>42</source_obj>
          <sink_obj>76</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_93">
          <id>483</id>
          <edge_type>4</edge_type>
          <source_obj>42</source_obj>
          <sink_obj>79</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_94">
          <id>484</id>
          <edge_type>4</edge_type>
          <source_obj>42</source_obj>
          <sink_obj>76</sink_obj>
        </item>
      </edges>
    </cdfg>
    <cdfg_regions class_id="21" tracking_level="0" version="0">
      <count>1</count>
      <item_version>0</item_version>
      <item class_id="22" tracking_level="1" version="0" object_id="_95">
        <mId>1</mId>
        <mTag>uart_wrapper_oled::uart_wrapper_oled</mTag>
        <mType>0</mType>
        <sub_regions>
          <count>0</count>
          <item_version>0</item_version>
        </sub_regions>
        <basic_blocks>
          <count>6</count>
          <item_version>0</item_version>
          <item>50</item>
          <item>56</item>
          <item>75</item>
          <item>78</item>
          <item>81</item>
          <item>83</item>
        </basic_blocks>
        <mII>-1</mII>
        <mDepth>-1</mDepth>
        <mMinTripCount>-1</mMinTripCount>
        <mMaxTripCount>-1</mMaxTripCount>
        <mMinLatency>780</mMinLatency>
        <mMaxLatency>-1</mMaxLatency>
        <mIsDfPipe>0</mIsDfPipe>
        <mDfPipe class_id="-1"/>
      </item>
    </cdfg_regions>
    <fsm class_id="24" tracking_level="1" version="0" object_id="_96">
      <states class_id="25" tracking_level="0" version="0">
        <count>5</count>
        <item_version>0</item_version>
        <item class_id="26" tracking_level="1" version="0" object_id="_97">
          <id>1</id>
          <operations class_id="27" tracking_level="0" version="0">
            <count>1</count>
            <item_version>0</item_version>
            <item class_id="28" tracking_level="1" version="0" object_id="_98">
              <id>42</id>
              <stage>2</stage>
              <latency>2</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="26" object_id="_99">
          <id>2</id>
          <operations>
            <count>53</count>
            <item_version>0</item_version>
            <item class_id_reference="28" object_id="_100">
              <id>20</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_101">
              <id>21</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_102">
              <id>22</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_103">
              <id>23</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_104">
              <id>24</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_105">
              <id>25</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_106">
              <id>26</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_107">
              <id>27</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_108">
              <id>28</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_109">
              <id>29</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_110">
              <id>30</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_111">
              <id>31</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_112">
              <id>32</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_113">
              <id>33</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_114">
              <id>34</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_115">
              <id>35</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_116">
              <id>36</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_117">
              <id>37</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_118">
              <id>38</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_119">
              <id>39</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_120">
              <id>40</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_121">
              <id>41</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_122">
              <id>42</id>
              <stage>1</stage>
              <latency>2</latency>
            </item>
            <item class_id_reference="28" object_id="_123">
              <id>43</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_124">
              <id>44</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_125">
              <id>45</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_126">
              <id>46</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_127">
              <id>47</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_128">
              <id>48</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_129">
              <id>49</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_130">
              <id>51</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_131">
              <id>52</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_132">
              <id>53</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_133">
              <id>54</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_134">
              <id>55</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_135">
              <id>57</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_136">
              <id>58</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_137">
              <id>59</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_138">
              <id>60</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_139">
              <id>61</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_140">
              <id>62</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_141">
              <id>63</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_142">
              <id>64</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_143">
              <id>65</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_144">
              <id>66</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_145">
              <id>67</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_146">
              <id>68</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_147">
              <id>69</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_148">
              <id>70</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_149">
              <id>71</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_150">
              <id>72</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_151">
              <id>73</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_152">
              <id>74</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="26" object_id="_153">
          <id>3</id>
          <operations>
            <count>1</count>
            <item_version>0</item_version>
            <item class_id_reference="28" object_id="_154">
              <id>76</id>
              <stage>2</stage>
              <latency>2</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="26" object_id="_155">
          <id>4</id>
          <operations>
            <count>5</count>
            <item_version>0</item_version>
            <item class_id_reference="28" object_id="_156">
              <id>76</id>
              <stage>1</stage>
              <latency>2</latency>
            </item>
            <item class_id_reference="28" object_id="_157">
              <id>77</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_158">
              <id>79</id>
              <stage>1</stage>
              <latency>2</latency>
            </item>
            <item class_id_reference="28" object_id="_159">
              <id>80</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_160">
              <id>82</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="26" object_id="_161">
          <id>5</id>
          <operations>
            <count>1</count>
            <item_version>0</item_version>
            <item class_id_reference="28" object_id="_162">
              <id>79</id>
              <stage>2</stage>
              <latency>2</latency>
            </item>
          </operations>
        </item>
      </states>
      <transitions class_id="29" tracking_level="0" version="0">
        <count>5</count>
        <item_version>0</item_version>
        <item class_id="30" tracking_level="1" version="0" object_id="_163">
          <inState>1</inState>
          <outState>2</outState>
          <condition class_id="31" tracking_level="0" version="0">
            <id>14</id>
            <sop class_id="32" tracking_level="0" version="0">
              <count>1</count>
              <item_version>0</item_version>
              <item class_id="33" tracking_level="0" version="0">
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="30" object_id="_164">
          <inState>2</inState>
          <outState>5</outState>
          <condition>
            <id>15</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>1</count>
                <item_version>0</item_version>
                <item class_id="34" tracking_level="0" version="0">
                  <first class_id="35" tracking_level="0" version="0">
                    <first>48</first>
                    <second>0</second>
                  </first>
                  <second>0</second>
                </item>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="30" object_id="_165">
          <inState>2</inState>
          <outState>3</outState>
          <condition>
            <id>17</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>2</count>
                <item_version>0</item_version>
                <item>
                  <first>
                    <first>48</first>
                    <second>0</second>
                  </first>
                  <second>1</second>
                </item>
                <item>
                  <first>
                    <first>54</first>
                    <second>0</second>
                  </first>
                  <second>0</second>
                </item>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="30" object_id="_166">
          <inState>3</inState>
          <outState>4</outState>
          <condition>
            <id>18</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="30" object_id="_167">
          <inState>5</inState>
          <outState>4</outState>
          <condition>
            <id>19</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
      </transitions>
    </fsm>
    <res class_id="36" tracking_level="1" version="0" object_id="_168">
      <dp_component_resource class_id="37" tracking_level="0" version="0">
        <count>3</count>
        <item_version>0</item_version>
        <item class_id="38" tracking_level="0" version="0">
          <first>grp_oled_process_fu_106 (oled_process)</first>
          <second class_id="39" tracking_level="0" version="0">
            <count>3</count>
            <item_version>0</item_version>
            <item class_id="40" tracking_level="0" version="0">
              <first>DSP48E</first>
              <second>2</second>
            </item>
            <item>
              <first>FF</first>
              <second>366</second>
            </item>
            <item>
              <first>LUT</first>
              <second>471</second>
            </item>
          </second>
        </item>
        <item>
          <first>grp_uart_wrapper_oled_do_action1_fu_164 (uart_wrapper_oled_do_action1)</first>
          <second>
            <count>2</count>
            <item_version>0</item_version>
            <item>
              <first>FF</first>
              <second>29</second>
            </item>
            <item>
              <first>LUT</first>
              <second>53</second>
            </item>
          </second>
        </item>
        <item>
          <first>grp_uart_wrapper_oled_do_action2_fu_128 (uart_wrapper_oled_do_action2)</first>
          <second>
            <count>2</count>
            <item_version>0</item_version>
            <item>
              <first>FF</first>
              <second>29</second>
            </item>
            <item>
              <first>LUT</first>
              <second>80</second>
            </item>
          </second>
        </item>
      </dp_component_resource>
      <dp_expression_resource>
        <count>0</count>
        <item_version>0</item_version>
      </dp_expression_resource>
      <dp_fifo_resource>
        <count>2</count>
        <item_version>0</item_version>
        <item>
          <first>FIFO_I_1_fifo_U</first>
          <second>
            <count>6</count>
            <item_version>0</item_version>
            <item>
              <first>(0Depth)</first>
              <second>192</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>32</second>
            </item>
            <item>
              <first>(2Size:D*B)</first>
              <second>6144</second>
            </item>
            <item>
              <first>BRAM</first>
              <second>2</second>
            </item>
            <item>
              <first>FF</first>
              <second>55</second>
            </item>
            <item>
              <first>LUT</first>
              <second>56</second>
            </item>
          </second>
        </item>
        <item>
          <first>FIFO_O_1_fifo_U</first>
          <second>
            <count>6</count>
            <item_version>0</item_version>
            <item>
              <first>(0Depth)</first>
              <second>192</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>32</second>
            </item>
            <item>
              <first>(2Size:D*B)</first>
              <second>6144</second>
            </item>
            <item>
              <first>BRAM</first>
              <second>2</second>
            </item>
            <item>
              <first>FF</first>
              <second>55</second>
            </item>
            <item>
              <first>LUT</first>
              <second>56</second>
            </item>
          </second>
        </item>
      </dp_fifo_resource>
      <dp_memory_resource>
        <count>0</count>
        <item_version>0</item_version>
      </dp_memory_resource>
      <dp_multiplexer_resource>
        <count>0</count>
        <item_version>0</item_version>
      </dp_multiplexer_resource>
      <dp_register_resource>
        <count>0</count>
        <item_version>0</item_version>
      </dp_register_resource>
      <dp_dsp_resource>
        <count>3</count>
        <item_version>0</item_version>
        <item>
          <first>grp_oled_process_fu_106</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
        <item>
          <first>grp_uart_wrapper_oled_do_action1_fu_164</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
        <item>
          <first>grp_uart_wrapper_oled_do_action2_fu_128</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
      </dp_dsp_resource>
      <dp_component_map class_id="41" tracking_level="0" version="0">
        <count>3</count>
        <item_version>0</item_version>
        <item class_id="42" tracking_level="0" version="0">
          <first>grp_oled_process_fu_106 (oled_process)</first>
          <second>
            <count>1</count>
            <item_version>0</item_version>
            <item>42</item>
          </second>
        </item>
        <item>
          <first>grp_uart_wrapper_oled_do_action1_fu_164 (uart_wrapper_oled_do_action1)</first>
          <second>
            <count>1</count>
            <item_version>0</item_version>
            <item>79</item>
          </second>
        </item>
        <item>
          <first>grp_uart_wrapper_oled_do_action2_fu_128 (uart_wrapper_oled_do_action2)</first>
          <second>
            <count>1</count>
            <item_version>0</item_version>
            <item>76</item>
          </second>
        </item>
      </dp_component_map>
      <dp_expression_map>
        <count>0</count>
        <item_version>0</item_version>
      </dp_expression_map>
      <dp_fifo_map>
        <count>2</count>
        <item_version>0</item_version>
        <item>
          <first>FIFO_I_1_fifo_U</first>
          <second>
            <count>1</count>
            <item_version>0</item_version>
            <item>129</item>
          </second>
        </item>
        <item>
          <first>FIFO_O_1_fifo_U</first>
          <second>
            <count>1</count>
            <item_version>0</item_version>
            <item>131</item>
          </second>
        </item>
      </dp_fifo_map>
      <dp_memory_map>
        <count>0</count>
        <item_version>0</item_version>
      </dp_memory_map>
    </res>
    <node_label_latency class_id="43" tracking_level="0" version="0">
      <count>11</count>
      <item_version>0</item_version>
      <item class_id="44" tracking_level="0" version="0">
        <first>42</first>
        <second class_id="45" tracking_level="0" version="0">
          <first>0</first>
          <second>1</second>
        </second>
      </item>
      <item>
        <first>48</first>
        <second>
          <first>1</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>49</first>
        <second>
          <first>1</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>54</first>
        <second>
          <first>1</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>55</first>
        <second>
          <first>1</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>74</first>
        <second>
          <first>1</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>76</first>
        <second>
          <first>2</first>
          <second>1</second>
        </second>
      </item>
      <item>
        <first>77</first>
        <second>
          <first>3</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>79</first>
        <second>
          <first>2</first>
          <second>1</second>
        </second>
      </item>
      <item>
        <first>80</first>
        <second>
          <first>3</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>82</first>
        <second>
          <first>3</first>
          <second>0</second>
        </second>
      </item>
    </node_label_latency>
    <bblk_ent_exit class_id="46" tracking_level="0" version="0">
      <count>6</count>
      <item_version>0</item_version>
      <item class_id="47" tracking_level="0" version="0">
        <first>50</first>
        <second class_id="48" tracking_level="0" version="0">
          <first>0</first>
          <second>1</second>
        </second>
      </item>
      <item>
        <first>56</first>
        <second>
          <first>1</first>
          <second>1</second>
        </second>
      </item>
      <item>
        <first>75</first>
        <second>
          <first>1</first>
          <second>1</second>
        </second>
      </item>
      <item>
        <first>78</first>
        <second>
          <first>2</first>
          <second>3</second>
        </second>
      </item>
      <item>
        <first>81</first>
        <second>
          <first>2</first>
          <second>3</second>
        </second>
      </item>
      <item>
        <first>83</first>
        <second>
          <first>3</first>
          <second>3</second>
        </second>
      </item>
    </bblk_ent_exit>
    <regions class_id="49" tracking_level="0" version="0">
      <count>0</count>
      <item_version>0</item_version>
    </regions>
    <dp_fu_nodes class_id="50" tracking_level="0" version="0">
      <count>5</count>
      <item_version>0</item_version>
      <item class_id="51" tracking_level="0" version="0">
        <first>106</first>
        <second>
          <count>2</count>
          <item_version>0</item_version>
          <item>42</item>
          <item>42</item>
        </second>
      </item>
      <item>
        <first>128</first>
        <second>
          <count>2</count>
          <item_version>0</item_version>
          <item>76</item>
          <item>76</item>
        </second>
      </item>
      <item>
        <first>164</first>
        <second>
          <count>2</count>
          <item_version>0</item_version>
          <item>79</item>
          <item>79</item>
        </second>
      </item>
      <item>
        <first>200</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>48</item>
        </second>
      </item>
      <item>
        <first>204</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>54</item>
        </second>
      </item>
    </dp_fu_nodes>
    <dp_fu_nodes_expression class_id="53" tracking_level="0" version="0">
      <count>0</count>
      <item_version>0</item_version>
    </dp_fu_nodes_expression>
    <dp_fu_nodes_module>
      <count>3</count>
      <item_version>0</item_version>
      <item class_id="54" tracking_level="0" version="0">
        <first>grp_oled_process_fu_106</first>
        <second>
          <count>2</count>
          <item_version>0</item_version>
          <item>42</item>
          <item>42</item>
        </second>
      </item>
      <item>
        <first>grp_uart_wrapper_oled_do_action1_fu_164</first>
        <second>
          <count>2</count>
          <item_version>0</item_version>
          <item>79</item>
          <item>79</item>
        </second>
      </item>
      <item>
        <first>grp_uart_wrapper_oled_do_action2_fu_128</first>
        <second>
          <count>2</count>
          <item_version>0</item_version>
          <item>76</item>
          <item>76</item>
        </second>
      </item>
    </dp_fu_nodes_module>
    <dp_fu_nodes_io>
      <count>2</count>
      <item_version>0</item_version>
      <item>
        <first>uart_wrapper_oled_1_load_fu_204</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>54</item>
        </second>
      </item>
      <item>
        <first>uart_wrapper_oled_s_load_fu_200</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>48</item>
        </second>
      </item>
    </dp_fu_nodes_io>
    <return_ports>
      <count>0</count>
      <item_version>0</item_version>
    </return_ports>
    <dp_mem_port_nodes class_id="55" tracking_level="0" version="0">
      <count>0</count>
      <item_version>0</item_version>
    </dp_mem_port_nodes>
    <dp_reg_nodes>
      <count>1</count>
      <item_version>0</item_version>
      <item>
        <first>208</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>48</item>
        </second>
      </item>
    </dp_reg_nodes>
    <dp_regname_nodes>
      <count>1</count>
      <item_version>0</item_version>
      <item>
        <first>uart_wrapper_oled_s_reg_208</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>48</item>
        </second>
      </item>
    </dp_regname_nodes>
    <dp_reg_phi>
      <count>0</count>
      <item_version>0</item_version>
    </dp_reg_phi>
    <dp_regname_phi>
      <count>0</count>
      <item_version>0</item_version>
    </dp_regname_phi>
    <dp_port_io_nodes class_id="56" tracking_level="0" version="0">
      <count>6</count>
      <item_version>0</item_version>
      <item class_id="57" tracking_level="0" version="0">
        <first>clk</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>
            <first>call</first>
            <second>
              <count>2</count>
              <item_version>0</item_version>
              <item>79</item>
              <item>76</item>
            </second>
          </item>
        </second>
      </item>
      <item>
        <first>e</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>
            <first>call</first>
            <second>
              <count>2</count>
              <item_version>0</item_version>
              <item>79</item>
              <item>76</item>
            </second>
          </item>
        </second>
      </item>
      <item>
        <first>en</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>
            <first>call</first>
            <second>
              <count>2</count>
              <item_version>0</item_version>
              <item>79</item>
              <item>76</item>
            </second>
          </item>
        </second>
      </item>
      <item>
        <first>reset</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>
            <first>call</first>
            <second>
              <count>2</count>
              <item_version>0</item_version>
              <item>79</item>
              <item>76</item>
            </second>
          </item>
        </second>
      </item>
      <item>
        <first>s</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>
            <first>call</first>
            <second>
              <count>2</count>
              <item_version>0</item_version>
              <item>79</item>
              <item>76</item>
            </second>
          </item>
        </second>
      </item>
      <item>
        <first>s_i</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>
            <first>call</first>
            <second>
              <count>2</count>
              <item_version>0</item_version>
              <item>79</item>
              <item>76</item>
            </second>
          </item>
        </second>
      </item>
    </dp_port_io_nodes>
    <port2core class_id="58" tracking_level="0" version="0">
      <count>2</count>
      <item_version>0</item_version>
      <item class_id="59" tracking_level="0" version="0">
        <first>3</first>
        <second>FIFO_SRL</second>
      </item>
      <item>
        <first>4</first>
        <second>FIFO_SRL</second>
      </item>
    </port2core>
    <node2core>
      <count>0</count>
      <item_version>0</item_version>
    </node2core>
  </syndb>
</boost_serialization>
