# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lucas/Documents/Projet_avance_SE/Lucas_commit/rtl_uart_nexys_4/vivado/rtl_uart.srcs/sources_1/ip/Conversion_0/Conversion_0.xci
# IP: The module: 'Conversion_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lucas/Documents/Projet_avance_SE/Lucas_commit/rtl_uart_nexys_4/vivado/rtl_uart.srcs/sources_1/ip/Conversion_0/constraints/Conversion_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Conversion_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/lucas/Documents/Projet_avance_SE/Lucas_commit/rtl_uart_nexys_4/vivado/rtl_uart.srcs/sources_1/ip/Conversion_0/Conversion_0.xci
# IP: The module: 'Conversion_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lucas/Documents/Projet_avance_SE/Lucas_commit/rtl_uart_nexys_4/vivado/rtl_uart.srcs/sources_1/ip/Conversion_0/constraints/Conversion_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Conversion_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
