// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.3
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="carre,hls_ip_2017_3,{HLS_INPUT_TYPE=sc,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100tcsg324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.784000,HLS_SYN_LAT=4,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=3,HLS_SYN_FF=214,HLS_SYN_LUT=196}" *)

module carre (
        clk,
        reset,
        e_dout,
        e_empty_n,
        e_read,
        s_din,
        s_full_n,
        s_write
);


input   clk;
input   reset;
input  [31:0] e_dout;
input   e_empty_n;
output   e_read;
output  [31:0] s_din;
input   s_full_n;
output   s_write;

wire   [31:0] grp_carre_do_carre_fu_58_carre_x;
wire    grp_carre_do_carre_fu_58_carre_x_ap_vld;
wire    grp_carre_do_carre_fu_58_e_read;
wire   [31:0] grp_carre_do_carre_fu_58_s_din;
wire    grp_carre_do_carre_fu_58_s_write;

carre_do_carre grp_carre_do_carre_fu_58(
    .ap_clk(clk),
    .ap_rst(reset),
    .carre_x(grp_carre_do_carre_fu_58_carre_x),
    .carre_x_ap_vld(grp_carre_do_carre_fu_58_carre_x_ap_vld),
    .e_dout(e_dout),
    .e_empty_n(e_empty_n),
    .e_read(grp_carre_do_carre_fu_58_e_read),
    .s_din(grp_carre_do_carre_fu_58_s_din),
    .s_full_n(s_full_n),
    .s_write(grp_carre_do_carre_fu_58_s_write)
);

assign e_read = grp_carre_do_carre_fu_58_e_read;

assign s_din = grp_carre_do_carre_fu_58_s_din;

assign s_write = grp_carre_do_carre_fu_58_s_write;

endmodule //carre
