// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.3
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="filtre2,hls_ip_2017_3,{HLS_INPUT_TYPE=sc,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100tcsg324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.608000,HLS_SYN_LAT=12,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=25,HLS_SYN_FF=2070,HLS_SYN_LUT=1703}" *)

module filtre2 (
        ap_clk,
        ap_rst,
        clk,
        reset,
        e_dout,
        e_empty_n,
        e_read,
        s_din,
        s_full_n,
        s_write
);


input   ap_clk;
input   ap_rst;
input   clk;
input   reset;
input  [31:0] e_dout;
input   e_empty_n;
output   e_read;
output  [31:0] s_din;
input   s_full_n;
output   s_write;

wire   [31:0] grp_filtre2_do_filtre_fu_64_filtre2_y0;
wire    grp_filtre2_do_filtre_fu_64_filtre2_y0_ap_vld;
wire   [31:0] grp_filtre2_do_filtre_fu_64_filtre2_x0;
wire    grp_filtre2_do_filtre_fu_64_filtre2_x0_ap_vld;
wire   [0:0] grp_filtre2_do_filtre_fu_64_filtre2_mem_x_address0;
wire    grp_filtre2_do_filtre_fu_64_filtre2_mem_x_ce0;
wire    grp_filtre2_do_filtre_fu_64_filtre2_mem_x_we0;
wire   [31:0] grp_filtre2_do_filtre_fu_64_filtre2_mem_x_d0;
wire   [0:0] grp_filtre2_do_filtre_fu_64_filtre2_mem_y_address0;
wire    grp_filtre2_do_filtre_fu_64_filtre2_mem_y_ce0;
wire    grp_filtre2_do_filtre_fu_64_filtre2_mem_y_we0;
wire   [31:0] grp_filtre2_do_filtre_fu_64_filtre2_mem_y_d0;
wire    grp_filtre2_do_filtre_fu_64_e_read;
wire   [31:0] grp_filtre2_do_filtre_fu_64_s_din;
wire    grp_filtre2_do_filtre_fu_64_s_write;

filtre2_filtre2_mlbW #(
    .DataWidth( 32 ),
    .AddressRange( 1 ),
    .AddressWidth( 1 ))
filtre2_mem_x_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_filtre2_do_filtre_fu_64_filtre2_mem_x_address0),
    .ce0(grp_filtre2_do_filtre_fu_64_filtre2_mem_x_ce0),
    .we0(grp_filtre2_do_filtre_fu_64_filtre2_mem_x_we0),
    .d0(grp_filtre2_do_filtre_fu_64_filtre2_mem_x_d0)
);

filtre2_filtre2_mlbW #(
    .DataWidth( 32 ),
    .AddressRange( 1 ),
    .AddressWidth( 1 ))
filtre2_mem_y_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_filtre2_do_filtre_fu_64_filtre2_mem_y_address0),
    .ce0(grp_filtre2_do_filtre_fu_64_filtre2_mem_y_ce0),
    .we0(grp_filtre2_do_filtre_fu_64_filtre2_mem_y_we0),
    .d0(grp_filtre2_do_filtre_fu_64_filtre2_mem_y_d0)
);

filtre2_do_filtre grp_filtre2_do_filtre_fu_64(
    .ap_clk(clk),
    .ap_rst(reset),
    .filtre2_y0(grp_filtre2_do_filtre_fu_64_filtre2_y0),
    .filtre2_y0_ap_vld(grp_filtre2_do_filtre_fu_64_filtre2_y0_ap_vld),
    .filtre2_x0(grp_filtre2_do_filtre_fu_64_filtre2_x0),
    .filtre2_x0_ap_vld(grp_filtre2_do_filtre_fu_64_filtre2_x0_ap_vld),
    .filtre2_mem_x_address0(grp_filtre2_do_filtre_fu_64_filtre2_mem_x_address0),
    .filtre2_mem_x_ce0(grp_filtre2_do_filtre_fu_64_filtre2_mem_x_ce0),
    .filtre2_mem_x_we0(grp_filtre2_do_filtre_fu_64_filtre2_mem_x_we0),
    .filtre2_mem_x_d0(grp_filtre2_do_filtre_fu_64_filtre2_mem_x_d0),
    .filtre2_mem_y_address0(grp_filtre2_do_filtre_fu_64_filtre2_mem_y_address0),
    .filtre2_mem_y_ce0(grp_filtre2_do_filtre_fu_64_filtre2_mem_y_ce0),
    .filtre2_mem_y_we0(grp_filtre2_do_filtre_fu_64_filtre2_mem_y_we0),
    .filtre2_mem_y_d0(grp_filtre2_do_filtre_fu_64_filtre2_mem_y_d0),
    .e_dout(e_dout),
    .e_empty_n(e_empty_n),
    .e_read(grp_filtre2_do_filtre_fu_64_e_read),
    .s_din(grp_filtre2_do_filtre_fu_64_s_din),
    .s_full_n(s_full_n),
    .s_write(grp_filtre2_do_filtre_fu_64_s_write)
);

assign e_read = grp_filtre2_do_filtre_fu_64_e_read;

assign s_din = grp_filtre2_do_filtre_fu_64_s_din;

assign s_write = grp_filtre2_do_filtre_fu_64_s_write;

endmodule //filtre2
