# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Nexys4_Master.xdc

# IP: ip/uart_wrapper_0_4/uart_wrapper_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_wrapper_0 || ORIG_REF_NAME==uart_wrapper_0} -quiet] -quiet
