-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.3
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity doubleur is
port (
    clk : IN STD_LOGIC;
    reset : IN STD_LOGIC;
    e_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    e_empty_n : IN STD_LOGIC;
    e_read : OUT STD_LOGIC;
    s1_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    s1_full_n : IN STD_LOGIC;
    s1_write : OUT STD_LOGIC;
    s2_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    s2_full_n : IN STD_LOGIC;
    s2_write : OUT STD_LOGIC );
end;


architecture behav of doubleur is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "doubleur,hls_ip_2017_3,{HLS_INPUT_TYPE=sc,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100tcsg324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.816000,HLS_SYN_LAT=2,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=2,HLS_SYN_LUT=44}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal grp_doubleur_do_split_fu_70_doubleur_to_split : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_doubleur_do_split_fu_70_doubleur_to_split_ap_vld : STD_LOGIC;
    signal grp_doubleur_do_split_fu_70_e_read : STD_LOGIC;
    signal grp_doubleur_do_split_fu_70_s1_din : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_doubleur_do_split_fu_70_s1_write : STD_LOGIC;
    signal grp_doubleur_do_split_fu_70_s2_din : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_doubleur_do_split_fu_70_s2_write : STD_LOGIC;

    component doubleur_do_split IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        doubleur_to_split : OUT STD_LOGIC_VECTOR (31 downto 0);
        doubleur_to_split_ap_vld : OUT STD_LOGIC;
        e_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        e_empty_n : IN STD_LOGIC;
        e_read : OUT STD_LOGIC;
        s1_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        s1_full_n : IN STD_LOGIC;
        s1_write : OUT STD_LOGIC;
        s2_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        s2_full_n : IN STD_LOGIC;
        s2_write : OUT STD_LOGIC );
    end component;



begin
    grp_doubleur_do_split_fu_70 : component doubleur_do_split
    port map (
        ap_clk => clk,
        ap_rst => reset,
        doubleur_to_split => grp_doubleur_do_split_fu_70_doubleur_to_split,
        doubleur_to_split_ap_vld => grp_doubleur_do_split_fu_70_doubleur_to_split_ap_vld,
        e_dout => e_dout,
        e_empty_n => e_empty_n,
        e_read => grp_doubleur_do_split_fu_70_e_read,
        s1_din => grp_doubleur_do_split_fu_70_s1_din,
        s1_full_n => s1_full_n,
        s1_write => grp_doubleur_do_split_fu_70_s1_write,
        s2_din => grp_doubleur_do_split_fu_70_s2_din,
        s2_full_n => s2_full_n,
        s2_write => grp_doubleur_do_split_fu_70_s2_write);




    e_read <= grp_doubleur_do_split_fu_70_e_read;
    s1_din <= grp_doubleur_do_split_fu_70_s1_din;
    s1_write <= grp_doubleur_do_split_fu_70_s1_write;
    s2_din <= grp_doubleur_do_split_fu_70_s2_din;
    s2_write <= grp_doubleur_do_split_fu_70_s2_write;
end behav;
