// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.3
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="comparateur,hls_ip_2017_3,{HLS_INPUT_TYPE=sc,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100tcsg324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.074500,HLS_SYN_LAT=7,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=581,HLS_SYN_LUT=1196}" *)

module comparateur (
        clk,
        reset,
        e1_dout,
        e1_empty_n,
        e1_read,
        e2_dout,
        e2_empty_n,
        e2_read,
        s_din,
        s_full_n,
        s_write
);


input   clk;
input   reset;
input  [31:0] e1_dout;
input   e1_empty_n;
output   e1_read;
input  [31:0] e2_dout;
input   e2_empty_n;
output   e2_read;
output  [31:0] s_din;
input   s_full_n;
output   s_write;

wire   [31:0] grp_comparateur_do_comp_fu_74_comparateur_in1;
wire    grp_comparateur_do_comp_fu_74_comparateur_in1_ap_vld;
wire   [31:0] grp_comparateur_do_comp_fu_74_comparateur_seuil;
wire    grp_comparateur_do_comp_fu_74_comparateur_seuil_ap_vld;
wire   [31:0] grp_comparateur_do_comp_fu_74_comparateur_result;
wire    grp_comparateur_do_comp_fu_74_comparateur_result_ap_vld;
wire    grp_comparateur_do_comp_fu_74_e1_read;
wire    grp_comparateur_do_comp_fu_74_e2_read;
wire   [31:0] grp_comparateur_do_comp_fu_74_s_din;
wire    grp_comparateur_do_comp_fu_74_s_write;

comparateur_do_comp grp_comparateur_do_comp_fu_74(
    .ap_clk(clk),
    .ap_rst(reset),
    .comparateur_in1(grp_comparateur_do_comp_fu_74_comparateur_in1),
    .comparateur_in1_ap_vld(grp_comparateur_do_comp_fu_74_comparateur_in1_ap_vld),
    .comparateur_seuil(grp_comparateur_do_comp_fu_74_comparateur_seuil),
    .comparateur_seuil_ap_vld(grp_comparateur_do_comp_fu_74_comparateur_seuil_ap_vld),
    .comparateur_result(grp_comparateur_do_comp_fu_74_comparateur_result),
    .comparateur_result_ap_vld(grp_comparateur_do_comp_fu_74_comparateur_result_ap_vld),
    .e1_dout(e1_dout),
    .e1_empty_n(e1_empty_n),
    .e1_read(grp_comparateur_do_comp_fu_74_e1_read),
    .e2_dout(e2_dout),
    .e2_empty_n(e2_empty_n),
    .e2_read(grp_comparateur_do_comp_fu_74_e2_read),
    .s_din(grp_comparateur_do_comp_fu_74_s_din),
    .s_full_n(s_full_n),
    .s_write(grp_comparateur_do_comp_fu_74_s_write)
);

assign e1_read = grp_comparateur_do_comp_fu_74_e1_read;

assign e2_read = grp_comparateur_do_comp_fu_74_e2_read;

assign s_din = grp_comparateur_do_comp_fu_74_s_din;

assign s_write = grp_comparateur_do_comp_fu_74_s_write;

endmodule //comparateur
