# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: y:/Documents/MesDocuments/Cours_nsave/Enseirb-E3_nsave/pr310/git/Xavier_commit/vivado/main_module/main_module.srcs/sources_1/ip/top_level_0/top_level_0.xci
# IP: The module: 'top_level_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: y:/Documents/MesDocuments/Cours_nsave/Enseirb-E3_nsave/pr310/git/Xavier_commit/vivado/main_module/main_module.srcs/sources_1/ip/top_level_0/constraints/top_level_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: y:/Documents/MesDocuments/Cours_nsave/Enseirb-E3_nsave/pr310/git/Xavier_commit/vivado/main_module/main_module.srcs/sources_1/ip/top_level_0/top_level_0.xci
# IP: The module: 'top_level_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: y:/Documents/MesDocuments/Cours_nsave/Enseirb-E3_nsave/pr310/git/Xavier_commit/vivado/main_module/main_module.srcs/sources_1/ip/top_level_0/constraints/top_level_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
