// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.3
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module filtre1_do_filtre (
        ap_clk,
        ap_rst,
        filtre1_y0,
        filtre1_y0_ap_vld,
        filtre1_x0,
        filtre1_x0_ap_vld,
        filtre1_mem_x_address0,
        filtre1_mem_x_ce0,
        filtre1_mem_x_we0,
        filtre1_mem_x_d0,
        filtre1_mem_x_q0,
        filtre1_mem_x_address1,
        filtre1_mem_x_ce1,
        filtre1_mem_x_we1,
        filtre1_mem_x_d1,
        filtre1_mem_y_address0,
        filtre1_mem_y_ce0,
        filtre1_mem_y_we0,
        filtre1_mem_y_d0,
        filtre1_mem_y_q0,
        filtre1_mem_y_address1,
        filtre1_mem_y_ce1,
        filtre1_mem_y_we1,
        filtre1_mem_y_d1,
        e_dout,
        e_empty_n,
        e_read,
        s_din,
        s_full_n,
        s_write
);

parameter    ap_ST_fsm_state2 = 24'd2;
parameter    ap_ST_fsm_state3 = 24'd4;
parameter    ap_ST_fsm_state4 = 24'd8;
parameter    ap_ST_fsm_state5 = 24'd16;
parameter    ap_ST_fsm_state6 = 24'd32;
parameter    ap_ST_fsm_state7 = 24'd64;
parameter    ap_ST_fsm_state8 = 24'd128;
parameter    ap_ST_fsm_state9 = 24'd256;
parameter    ap_ST_fsm_state10 = 24'd512;
parameter    ap_ST_fsm_state11 = 24'd1024;
parameter    ap_ST_fsm_state12 = 24'd2048;
parameter    ap_ST_fsm_state13 = 24'd4096;
parameter    ap_ST_fsm_state14 = 24'd8192;
parameter    ap_ST_fsm_state15 = 24'd16384;
parameter    ap_ST_fsm_state16 = 24'd32768;
parameter    ap_ST_fsm_state17 = 24'd65536;
parameter    ap_ST_fsm_state18 = 24'd131072;
parameter    ap_ST_fsm_state19 = 24'd262144;
parameter    ap_ST_fsm_state20 = 24'd524288;
parameter    ap_ST_fsm_state21 = 24'd1048576;
parameter    ap_ST_fsm_state22 = 24'd2097152;
parameter    ap_ST_fsm_state23 = 24'd4194304;
parameter    ap_ST_fsm_state24 = 24'd8388608;

input   ap_clk;
input   ap_rst;
output  [31:0] filtre1_y0;
output   filtre1_y0_ap_vld;
output  [31:0] filtre1_x0;
output   filtre1_x0_ap_vld;
output  [0:0] filtre1_mem_x_address0;
output   filtre1_mem_x_ce0;
output   filtre1_mem_x_we0;
output  [31:0] filtre1_mem_x_d0;
input  [31:0] filtre1_mem_x_q0;
output  [0:0] filtre1_mem_x_address1;
output   filtre1_mem_x_ce1;
output   filtre1_mem_x_we1;
output  [31:0] filtre1_mem_x_d1;
output  [0:0] filtre1_mem_y_address0;
output   filtre1_mem_y_ce0;
output   filtre1_mem_y_we0;
output  [31:0] filtre1_mem_y_d0;
input  [31:0] filtre1_mem_y_q0;
output  [0:0] filtre1_mem_y_address1;
output   filtre1_mem_y_ce1;
output   filtre1_mem_y_we1;
output  [31:0] filtre1_mem_y_d1;
input  [31:0] e_dout;
input   e_empty_n;
output   e_read;
output  [31:0] s_din;
input   s_full_n;
output   s_write;

reg filtre1_y0_ap_vld;
reg filtre1_x0_ap_vld;
reg[0:0] filtre1_mem_x_address0;
reg filtre1_mem_x_ce0;
reg filtre1_mem_x_we0;
reg[0:0] filtre1_mem_x_address1;
reg filtre1_mem_x_ce1;
reg filtre1_mem_x_we1;
reg[31:0] filtre1_mem_x_d1;
reg[0:0] filtre1_mem_y_address0;
reg filtre1_mem_y_ce0;
reg filtre1_mem_y_we0;
reg[0:0] filtre1_mem_y_address1;
reg filtre1_mem_y_ce1;
reg filtre1_mem_y_we1;
reg[31:0] filtre1_mem_y_d1;
reg e_read;
reg s_write;

reg    e_blk_n;
(* fsm_encoding = "none" *) reg   [23:0] ap_CS_fsm;
wire    ap_CS_fsm_state3;
wire   [0:0] exitcond_fu_235_p2;
reg    s_blk_n;
wire    ap_CS_fsm_state24;
wire   [63:0] grp_fu_195_p1;
reg   [63:0] reg_218;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state10;
wire   [63:0] grp_fu_207_p2;
reg   [63:0] reg_223;
wire    ap_CS_fsm_state16;
wire   [63:0] grp_fu_203_p2;
reg   [63:0] reg_229;
wire    ap_CS_fsm_state22;
wire   [1:0] i_fu_241_p2;
reg   [1:0] i_reg_256;
reg    ap_block_state3;
reg   [31:0] val_reg_261;
reg   [0:0] filtre1_mem_y_addr_1_reg_268;
reg   [0:0] filtre1_mem_x_addr_1_reg_274;
wire   [63:0] tmp_4_fu_198_p1;
reg   [63:0] tmp_4_reg_280;
wire   [63:0] grp_fu_212_p2;
reg   [63:0] tmp_5_reg_285;
wire   [31:0] y_fu_191_p1;
reg   [31:0] y_reg_290;
wire    ap_CS_fsm_state23;
reg   [1:0] i1_reg_180;
wire    ap_CS_fsm_state2;
wire   [0:0] filtre1_mem_x_addr_gep_fu_111_p3;
wire   [0:0] filtre1_mem_y_addr_gep_fu_125_p3;
wire   [0:0] filtre1_mem_x_addr_2_gep_fu_139_p3;
wire   [0:0] filtre1_mem_y_addr_2_gep_fu_152_p3;
wire   [63:0] tmp_s_fu_247_p1;
wire    ap_CS_fsm_state9;
reg   [31:0] grp_fu_195_p0;
reg   [63:0] grp_fu_203_p0;
reg   [63:0] grp_fu_203_p1;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state17;
reg   [63:0] grp_fu_207_p1;
wire    ap_CS_fsm_state5;
reg   [1:0] grp_fu_203_opcode;
reg   [23:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 24'd2;
end

filtre1_fptrunc_6eOg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 64 ),
    .dout_WIDTH( 32 ))
filtre1_fptrunc_6eOg_U36(
    .din0(reg_229),
    .dout(y_fu_191_p1)
);

filtre1_fpext_32nfYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
filtre1_fpext_32nfYi_U37(
    .din0(grp_fu_195_p0),
    .dout(grp_fu_195_p1)
);

filtre1_fpext_32nfYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
filtre1_fpext_32nfYi_U38(
    .din0(filtre1_mem_x_q0),
    .dout(tmp_4_fu_198_p1)
);

filtre1_dadddsub_g8j #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
filtre1_dadddsub_g8j_U39(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_203_p0),
    .din1(grp_fu_203_p1),
    .opcode(grp_fu_203_opcode),
    .ce(1'b1),
    .dout(grp_fu_203_p2)
);

filtre1_dmul_64nshbi #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
filtre1_dmul_64nshbi_U40(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_218),
    .din1(grp_fu_207_p1),
    .ce(1'b1),
    .dout(grp_fu_207_p2)
);

filtre1_dmul_64nshbi #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
filtre1_dmul_64nshbi_U41(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_4_reg_280),
    .din1(64'd4607041681311662080),
    .ce(1'b1),
    .dout(grp_fu_212_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state2;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((s_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state24))) begin
        i1_reg_180 <= i_reg_256;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        i1_reg_180 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond_fu_235_p2 == 1'd0) & (1'b0 == e_empty_n)) & (exitcond_fu_235_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        filtre1_mem_x_addr_1_reg_274 <= tmp_s_fu_247_p1;
        filtre1_mem_y_addr_1_reg_268 <= tmp_s_fu_247_p1;
        val_reg_261 <= e_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond_fu_235_p2 == 1'd0) & (1'b0 == e_empty_n)) & (1'b1 == ap_CS_fsm_state3))) begin
        i_reg_256 <= i_fu_241_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state4))) begin
        reg_218 <= grp_fu_195_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state16))) begin
        reg_223 <= grp_fu_207_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state16))) begin
        reg_229 <= grp_fu_203_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        tmp_4_reg_280 <= tmp_4_fu_198_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        tmp_5_reg_285 <= grp_fu_212_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        y_reg_290 <= y_fu_191_p1;
    end
end

always @ (*) begin
    if (((exitcond_fu_235_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        e_blk_n = e_empty_n;
    end else begin
        e_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((exitcond_fu_235_p2 == 1'd0) & (1'b0 == e_empty_n)) & (exitcond_fu_235_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        e_read = 1'b1;
    end else begin
        e_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        filtre1_mem_x_address0 = tmp_s_fu_247_p1;
    end else if (~(1'b1 == 1'b1)) begin
        filtre1_mem_x_address0 = 64'd0;
    end else begin
        filtre1_mem_x_address0 = 'bx;
    end
end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        filtre1_mem_x_address1 = filtre1_mem_x_addr_1_reg_274;
    end else if (~(1'b1 == 1'b1)) begin
        filtre1_mem_x_address1 = 64'd1;
    end else begin
        filtre1_mem_x_address1 = 'bx;
    end
end
end

always @ (*) begin
    if ((~((exitcond_fu_235_p2 == 1'd0) & (1'b0 == e_empty_n)) & (1'b1 == ap_CS_fsm_state3))) begin
        filtre1_mem_x_ce0 = 1'b1;
    end else begin
        filtre1_mem_x_ce0 = 1'b0;
    end
end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        filtre1_mem_x_ce1 = 1'b1;
    end else begin
        filtre1_mem_x_ce1 = 1'b0;
    end
end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        filtre1_mem_x_d1 = val_reg_261;
    end else if (~(1'b1 == 1'b1)) begin
        filtre1_mem_x_d1 = 32'd0;
    end else begin
        filtre1_mem_x_d1 = 'bx;
    end
end
end

always @ (*) begin
    if (~(1'b1 == 1'b1)) begin
        filtre1_mem_x_we0 = 1'b1;
    end else begin
        filtre1_mem_x_we0 = 1'b0;
    end
end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        filtre1_mem_x_we1 = 1'b1;
    end else begin
        filtre1_mem_x_we1 = 1'b0;
    end
end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        filtre1_mem_y_address0 = filtre1_mem_y_addr_1_reg_268;
    end else if (~(1'b1 == 1'b1)) begin
        filtre1_mem_y_address0 = 64'd0;
    end else begin
        filtre1_mem_y_address0 = 'bx;
    end
end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        filtre1_mem_y_address1 = filtre1_mem_y_addr_1_reg_268;
    end else if (~(1'b1 == 1'b1)) begin
        filtre1_mem_y_address1 = 64'd1;
    end else begin
        filtre1_mem_y_address1 = 'bx;
    end
end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        filtre1_mem_y_ce0 = 1'b1;
    end else begin
        filtre1_mem_y_ce0 = 1'b0;
    end
end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        filtre1_mem_y_ce1 = 1'b1;
    end else begin
        filtre1_mem_y_ce1 = 1'b0;
    end
end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        filtre1_mem_y_d1 = y_fu_191_p1;
    end else if (~(1'b1 == 1'b1)) begin
        filtre1_mem_y_d1 = 32'd0;
    end else begin
        filtre1_mem_y_d1 = 'bx;
    end
end
end

always @ (*) begin
    if (~(1'b1 == 1'b1)) begin
        filtre1_mem_y_we0 = 1'b1;
    end else begin
        filtre1_mem_y_we0 = 1'b0;
    end
end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        filtre1_mem_y_we1 = 1'b1;
    end else begin
        filtre1_mem_y_we1 = 1'b0;
    end
end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        filtre1_x0_ap_vld = 1'b1;
    end else begin
        filtre1_x0_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((s_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state24))) begin
        filtre1_y0_ap_vld = 1'b1;
    end else begin
        filtre1_y0_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_195_p0 = filtre1_mem_y_q0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_195_p0 = val_reg_261;
    end else begin
        grp_fu_195_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_fu_203_opcode = 2'd1;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_203_opcode = 2'd0;
    end else begin
        grp_fu_203_opcode = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_203_p0 = reg_229;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_fu_203_p0 = reg_223;
    end else begin
        grp_fu_203_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_203_p1 = reg_223;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_fu_203_p1 = tmp_5_reg_285;
    end else begin
        grp_fu_203_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_fu_207_p1 = 64'd4606900943823306752;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_207_p1 = 64'd4607041681311662080;
    end else begin
        grp_fu_207_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        s_blk_n = s_full_n;
    end else begin
        s_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((s_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state24))) begin
        s_write = 1'b1;
    end else begin
        s_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if ((~((exitcond_fu_235_p2 == 1'd0) & (1'b0 == e_empty_n)) & (exitcond_fu_235_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if ((~((exitcond_fu_235_p2 == 1'd0) & (1'b0 == e_empty_n)) & (exitcond_fu_235_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            if (((s_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state24))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state3 = ((exitcond_fu_235_p2 == 1'd0) & (1'b0 == e_empty_n));
end

assign exitcond_fu_235_p2 = ((i1_reg_180 == 2'd2) ? 1'b1 : 1'b0);

assign filtre1_mem_x_addr_2_gep_fu_139_p3 = 64'd1;

assign filtre1_mem_x_addr_gep_fu_111_p3 = 64'd0;

assign filtre1_mem_x_d0 = 32'd0;

assign filtre1_mem_y_addr_2_gep_fu_152_p3 = 64'd1;

assign filtre1_mem_y_addr_gep_fu_125_p3 = 64'd0;

assign filtre1_mem_y_d0 = 32'd0;

assign filtre1_x0 = val_reg_261;

assign filtre1_y0 = y_reg_290;

assign i_fu_241_p2 = (i1_reg_180 + 2'd1);

assign s_din = y_reg_290;

assign tmp_s_fu_247_p1 = i1_reg_180;

endmodule //filtre1_do_filtre
